/*
-- Query: SELECT * FROM projectrailway.station
LIMIT 0, 1000

-- Date: 2021-01-16 23:55
*/
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('A N DEV NAGAR',' ACND');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ABHAIPUR',' AHA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ABOHAR',' ABS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ABU ROAD',' ABR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ACHALDA',' ULD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ACHHNERA JN',' AH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ADAVALI',' ADVI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ADESAR',' AAR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ADHARTAL',' ADTL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ADILABAD',' ADB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ADINA',' ADF');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ADIPUR',' AI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ADITYAPUR',' ADTP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ADONI',' AD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ADRA JN',' ADRA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ADRSH NGR DELHI',' ANDI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ADUTURAI',' ADT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AGARTALA',' AGTL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AGORI KHAS',' AGY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AGRA CANTT',' AGC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AGRA CITY',' AGA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AGRA FORT',' AF');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AHMADGARH',' AHH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AHMADNAGAR',' ANG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AHMADPUR JN',' AMP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AHMEDABAD JN',' ADI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AHRAURA ROAD',' ARW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AISHBAGH',' ASH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AIT',' AIT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AITHAL',' ATMO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AJMER JN',' AII');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AJNI',' AJNI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AKALKOT ROAD',' AKOR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AKALTARA',' AKT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AKANAPET',' AKE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AKBARGANJ',' AKJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AKBARNAGAR',' AKN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AKBARPUR',' ABP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AKIVIDU',' AKVD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AKODIA',' AKD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AKOLA JN',' AK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AKSHAYWAT R NGR',' AYRN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AKURDI',' AKRD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('alai',' ALJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALAMNAGAR',' AMG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALAMPUR',' ALMR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALER',' ALER');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALGAWAN',' AIG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALIA BADA',' ALB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALIGARH JN',' ALJN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALIPUR DUAR JN',' APDJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALLAHABAD CITY',' ALY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALLAHABAD JN',' ALD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALLEPPEY',' ALLP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALMATTI',' LMT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALNAVAR JN',' LWR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALUABARI ROAD',' AUB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALUVA',' AWY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ALWAR',' AWR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMALNER',' AN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMALSAD',' AML');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMARDA ROAD',' ARD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMARGARH',' AGR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMB ANDAURA',' AADR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMBALA CANT JN',' UMB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMBALA CITY',' UBC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMBALAPUZHA',' AMPA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMBALE',' ABLE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMBARI FALAKATA',' ABFC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMBARNATH',' ABH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMBASA',' ABSA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMBASAMUDRAM',' ASD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMBATURAI',' ABI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMBIKA KALNA',' ABKA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMBIKAPUR',' ABKP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMBLI ROAD',' ABD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMBODALA',' AMB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMBUR',' AB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMDARA',' UDR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMETHI',' AME');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMGAON',' AGN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMGURI',' AGI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMLA JN',' AMLA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMLAI',' AAL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMMANABROLU',' ANB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMMASANDRA',' AMSA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMONI',' AONI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMRAVATI',' AMI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMRITSAR JN',' ASR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AMROHA',' AMRO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANAKAPALLE',' AKP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANAND JN',' ANND');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANAND NAGAR',' ANDN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANAND VIHAR',' ANVR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANAND VIHAR TRM',' ANVT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANANDAPURAM',' ANF');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANANDPUR SAHIB',' ANSB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANANTAPUR',' ATP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANAPARTI',' APT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANARA',' ANR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANAS',' ANAS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANAVARDIKHANPET',' AVN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANDAL JN',' UDL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANDHERI',' ADH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANGADIPPURAM',' AAM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANGAMALI',' AFK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANGUL',' ANGL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANJAR',' AJE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANJHI SHAHABAD',' AJI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANKAI',' ANK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANKLESHWAR JN',' AKV');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANKOLA',' ANKL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANKORAH AKORHA',' ANH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANNAVARAM',' ANV');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANNIGERI',' NGR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANPARA',' ANPR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANTAH',' ATH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANTU',' ANTU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANUGRAHA N ROAD',' AUBR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ANUPPUR JN',' APR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AONLA',' AO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ARA',' ARA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ARAG',' ARAG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ARAKKONAM',' AJJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ARALVAYMOZHI',' AAY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ARARIYA COURT',' ARQ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ARAVALI ROAD',' AVRD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ARIGADA',' ARGD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ARIYALUR',' ALU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ARJUNI',' AJU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ARNI ROAD',' ARV');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ARSIKERE JN',' ASK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ARUMUGANERI',' ANY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ARUNACHAL',' ARCL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ASAFPUR',' AFR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ASALPUR JOBNER',' JOB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ASANSOL JN',' ASN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ASAOTI',' AST');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ASARVA JN',' ASV');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ASHAPURA GOMAT',' AQG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ASHOK NAGAR',' ASKN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ASIFABAD ROAD',' ASAF');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ASLANA',' ANA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ASRANADA',' AAS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ATARI',' ATT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ATARRA',' ATE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ATHMAL GOLA',' ATL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ATTABIRA',' ATS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ATTILI',' AL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ATTUR',' ATU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AUNG',' AUNG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AUNRIHAR JN',' ARJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AURANGABAD',' AWB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AVADI',' AVD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AWATARNAGAR',' ATNR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AYODHYA',' AY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AYODHYAPATTANAM',' APN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AZAMGARH',' AMH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AZAMNAGAR ROAD',' AZR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('AZIMGANJ JN',' AZ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('B CEMENT NAGAR',' BEY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BABATPUR',' BTP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BABHNAN',' BV');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BABINA',' BAB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BABRALA',' BBA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BABUPETH',' BUPH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BACHHRAWAN',' BCN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BACHWARA JN',' BCA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADABANDHA',' BDBA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADAMI',' BDM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADARPUR JN',' BPB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADARWAS',' BDWS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADHWA BARA',' BDWA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADLA GHAT',' BHB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADLAPUR',' BUD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADLI',' BHD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADMAL',' BUDM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADNAPUR',' BDU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADNERA JN',' BD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADODAR',' BDDR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADSHAHNAGAR',' BNZ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADSHAHPUR',' BSE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BADULIPAR',' BLPR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAGAHA',' BUG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAGALKOT',' BGK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAGBAHRA',' BGBR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAGDIHI',' BEH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAGETAR',' BF');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAGEVADI RD',' BSRX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAGHAULI',' BGH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAGHDOGRA',' BORA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAGHORA',' BJQ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAGHUAPAL',' BGPL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAGNAN',' BZN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAGRA TAWA',' BGTA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAHADUR SINGH W',' BSS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAHADURGARH',' BGZ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAHJOI',' BJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAHRAICH',' BRK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAIDYANATHDHAM',' BDME');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAIGUDA',' BGUA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAIHATOLA',' BATL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAIKUNTHPUR RD',' BRH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAIRAGARH',' BIH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAITARANI ROAD',' BTV');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAJUD',' BJUD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAJVA',' BJW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAKHLETA',' BQQ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAKHTIYARPUR JN',' BKP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BALAGHAT JN',' BTC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BALAMU JN',' BLM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BALANGIR',' BLGR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BALASORE',' BLS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BALAWALI',' BLW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BALHARSHAH',' BPQ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BALLABGARH',' BVH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BALLIA',' BUI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BALOD',' BXA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BALOTRA JN',' BLT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BALPUR HALT',' BPRH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BALUGAN',' BALU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BALURGHAT',' BLGT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAMHRAULI',' BMU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAMLA',' BMLL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAMNIA',' BMI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAMRA',' BMB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANAHI',' BYN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANAPURA',' BPF');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANAR',' BNO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANASWADI',' BAND');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANBASA',' BNSA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANDA JN',' BNDA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANDAKPUR',' BNU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANDANWARA',' BDW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANDARKHAL',' BXK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANDEL JN',' BDC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANDIKUI JN',' BKI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANDRA TERMINUS',' BDTS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANGALORE CANT',' BNC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANGALORE CY JN',' SBC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANGALORE EAST',' BNCE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANGARAPET',' BWT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANGRIPOSI',' BGY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANGROD',' BOD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANI',' BANI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANKA',' BAKA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANKA GHAT',' BKG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANKATA',' BTK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANKHEDI',' BKH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANKURA',' BQA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANMOR',' BAO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANO',' BANO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANSIPUR',' BSQP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANSPANI',' BSPX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANSTHALI NIWAI',' BNLW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANTAWALA',' BNTL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BANTHRA',' BTRA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAPATLA',' BPP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAPUDM MOTIHARI',' BMKI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARA JAMDA',' BJMD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARABANKI JN',' BBK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARABHUM',' BBM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARABIL',' BBN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARADWAR',' BUA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARAGOPAL',' BAGL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARAHAT',' BHLE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARAIGRAM JN',' BRGM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARAKAR',' BRR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARAL',' BARL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARAN',' BAZ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARANG',' BRAG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARARA',' RAA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARAUNI JN',' BJU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARAUT',' BTU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARBATPUR',' BBTR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARCHI ROAD',' BCRD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARDDHAMAN JN',' BWN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARDOLI',' BIY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAREILLY',' BE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAREILLY CITY',' BC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAREJADI',' BJD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARELIPUR',' BQM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARETA',' BRZ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARETH',' BET');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARGARH',' BRG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARGARH ROAD',' BRGA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARGAWAN',' BRGW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARGI',' BUQ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARH',' BARH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARHARWA JN',' BHW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARHIYA',' BRYA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARHNI',' BNY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARI BRAHMAN',' BBMN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARIARPUR',' BUP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARIPADA',' BPO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARKA KANA',' BRKA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARKHERA',' BKA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARKISALALYA',' BSYA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARKUR',' BKJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARLAI',' BLAX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARMER',' BME');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARNALA',' BNN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAROG',' BOF');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARPALI',' BRPL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARPATHAR',' BXP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARPETA ROAD',' BPRD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARRACKPORE',' BP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARRAJPUR',' BJR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARSALI',' BYS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARSI TOWN',' BTW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARSOI JN',' BOE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARSOLA',' BZO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARUA BAMUNGAON',' BBGN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARUD',' BRUD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARWA SAGAR',' BWR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARWADIH JN',' BRWD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BARWALA',' BXC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BASAI',' BZY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BASANTAPUR',' BSTP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BASAR',' BSX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BASBARI',' BSI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BASHARATGANJ',' BTG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BASMAT',' BMF');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BASNI',' BANE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BASSI',' BAI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BASSI PATHANAM',' BSPN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BASTA',' BTS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BASTI',' BST');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BASUGAON',' BSGN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BASUKINATH',' BSKH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BASWA',' BU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BATALA JN',' BAT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAWAL',' BWL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAYANA JN',' BXN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAYTU',' BUT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BAZARSAU',' BZLE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BEAS',' BEAS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BEAWAR',' BER');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BEGAMPET',' BMT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BEGU SARAI',' BGS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BEHTAGOKUL',' BEG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BEKAL FORT',' BFR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BELA',' BELA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BELA TAL',' BTX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BELAKOBA',' BLK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BELAMPALLI',' BPA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BELAPUR',' BAP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BELDA',' BLDA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BELDANGA',' BEB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BELGAHNA',' BIG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BELGAUM',' BGM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BELHA',' BYL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BELLARY JN',' BAY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BELPAHAR',' BPH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BELRAYAN',' BXM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BELTHARA ROAD',' BLTR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BEOHARI',' BEHR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BERCHHA',' BCH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BERHAMPORE CRT',' BPC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BERMO',' BRMO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BETAMCHERLA',' BMH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BETHAMPURDI',' BTPD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BETHUADAHARI',' BTY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BETNOTI',' BTQ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BETTIAH',' BTH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BETUL',' BZU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHABHAR',' BAH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHABUA ROAD',' BBU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHACHAU BG',' BCOB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHADAN',' BDN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHADAURA',' BWH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHADOHI',' BOY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHADRACHALAM RD',' BDCR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHADRAK',' BHC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHADRAVATI',' BDVT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHAGA JN',' VAA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHAGALPUR',' BGP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHAGAT KI KOTHI',' BGKT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHAGWANGOLA',' BQG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHAGWANPUR',' BNR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHAIROGANJ',' BRU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHAIRONGARH',' BOG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHAKTI NAGAR',' BKNG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHALKI',' BHLK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHALUI',' BFM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHALUKA ROAD F',' BKRD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHALUKMARA',' BLMR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHALUMASKA',' BLMK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHANAPUR',' BNP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHANDAK',' BUX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHANDARA ROAD',' BRD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHANDARIDAH',' BHME');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHANVAD',' BNVD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHANWAR TONK',' BHTK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHARAT KUP',' BTKP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHARATPUR JN',' BTE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHARTHANA',' BNT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHARUCH JN',' BH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHARWA SUMERPUR',' BSZ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHARWARI',' BRE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHATAPARA',' BYT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHATINDA JN',' BTI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHATIYA',' BHTA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHATKAL',' BTJL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHATNI JN',' BTT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHATPAR RANI',' BHTR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHATTU',' BHT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHAVANAGAR PARA',' BVP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHAVANI NAGAR',' BVNR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHAVNAGAR TRMUS',' BVC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHAWANI MANDI',' BWM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHAWANIPATNA',' BWIP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHAYAVADAR',' BHY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHEDIA',' BDH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHERAGHAT',' BRGT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHIGWAN',' BGVN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHILAD',' BLD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHILAI',' BIA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHILAI PWR HS',' BPHB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHILAINAGAR',' BQR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHILAVDI',' BVQ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHILDI',' BLDI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHILWARA',' BHL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHIMADOLU',' BMD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHIMASAR BG',' BMSB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHIMAVARAM JN',' BVRM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHIMAVARAM TOWN',' BVRT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHIMSEN',' BZM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHIND',' BIX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHIRA KHERI',' BIK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHITONI',' BHTN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHIWANDI ROAD',' BIRD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHIWANI',' BNW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHIWANI CITY',' BNWC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHOJIPURA JN',' BPR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHOJO',' BOJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHOJUDIH JN',' BJE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHOKAR',' BOKR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHONGAON',' BGQ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHONGIR',' BG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHOPAL JN',' BPL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHORAS BUDRUKH',' BFJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHUBANESWAR',' BBS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHUCHCHU',' BCU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHUGAON',' BPK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHUJ',' BHUJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHULANPUR',' BHLP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHUPIA MAU',' VPO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHURKUNDA',' BHKD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHUSANDPUR',' BSDP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BHUSAVAL JN',' BSL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIBINAGAR',' BN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BICHIA',' BIC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIDADI',' BID');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIDAR',' BIDR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIDHAN NAGAR',' BNXR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIGHAPUR',' BQP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIHAR SHARIF',' BEHS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIHARA',' BHZ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIHIYA',' BEA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIHTA',' BTA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIJAINAGAR',' BJNR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIJAPUR',' BJP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIJAYSOTA',' VST');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIJNI',' BJF');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIJNOR',' BJO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIJOOR',' BIJR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIJURI',' BJRI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIJWASAN',' BWSN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIKANER JN',' BKN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIKKAVOLU',' BVL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIKRAM SHILA',' BKSL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIKRAMPUR',' BMR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BILASPUR JN',' BSP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BILASPUR ROAD',' BLQR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BILDI',' BILD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BILGA',' BZG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BILHAR GHAT',' BLG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BILHAUR',' BLU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BILIMORA JN',' BIM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BILPUR',' BLPU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BILWAI',' BWI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BINA JN',' BINA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BINDKI ROAD',' BKO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BINNAGURI',' BNV');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIRADHWAL',' BDWL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIRAPATTI',' BRPT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIRSINGHPUR',' BRS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIRUR JN',' RRB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BISHNATHGANJ',' BTJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BISHNUPUR',' VSU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BISHRAMPUR',' BSPR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BISRA',' BZR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BISSAMCUTTACK',' BMCK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BISUGIRSHARIF',' BGSF');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BISWAN',' BVN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BITRAGUNTA',' BTTR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BIYAVRA RAJGARH',' BRRG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BOBBILI',' VBL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BODHADI BUJRUG',' BHBK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BODWAD',' BDWD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BOHALI',' BHLI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BOHANI',' BNE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BOINDA',' BONA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BOISAR',' BOR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BOKAJAN',' BXJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BOKARO STL CITY',' BKSC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BOKARO THERMAL',' BKRO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BOLARUM',' BMO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BOLINNA DOABA',' BLND');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BOLPUR S NIKTN',' BHP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BOMMIDI',' BQI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BONA KALU',' BKL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BONDAMUNDA',' BNDM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BONGAIGAON',' BNGN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BORDHAL',' BXY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BORDI',' BIO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BORHAT',' BFD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BORIDAND',' BRND');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BORIVALI',' BVI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BORVIHIR',' BRVR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BOTAD JN',' BTD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BRAHMAPUR',' BAM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BRAJRAJNAGAR',' BRJN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BUDALUR',' BAL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BUDAUN',' BEM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BUDDIREDDIPPATI',' BDY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BUDHI',' BDHY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BUDHLADA',' BLZ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BUDNI',' BNI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BUDVEL',' BDVL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BULANDSHAHR',' BSC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BUNDI',' BUDI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BUNIADPUR',' BNDP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BURHANPUR',' BAU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BURHAR',' BUH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BURHWAL',' BUW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BURNPUR',' BURN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BUTARI',' BTR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BUTI BORI',' BTBR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BUXAR',' BXR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('BYADGI',' BYD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('C SHAHUMHARAJ T',' KOP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CANCONA',' CNO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CARMELARAM',' CRLM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CASTLE ROCK',' CLR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHABUA',' CHB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHACHAURA BNGJ',' CBK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAIBASA',' CBSA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAINPUR',' CNPR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAINWA',' CW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAJLI',' CJL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAKARPUR',' CKK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAKDAYALA',' CKDL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAKIA',' CAA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAKKI BANK',' CHKB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAKRADHARPUR',' CKP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAKULIA',' CKU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHALAKUDI',' CKI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHALISGAON JN',' CSN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAMPA',' CPH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAMPANER RD JN',' CPN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAND SIAU',' CPS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDA FORT',' CAF');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDAN NAGAR',' CGR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDAULI MJHWR',' CDMR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDAUSI JN',' CH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDERIYA',' CNA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDI MANDIR',' CNDM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDIA ROAD',' CHD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDIGARH',' CDG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDIL JN',' CNI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDLODIYA',' CLDY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDOK',' CNK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDRAKONA RD',' CDGR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDRANATHPUR',' CNE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDRAPUR',' CD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDRAPURA',' CRP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDUR',' CND');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANDUR BAZAR',' CNDB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANGANASERI',' CGY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANNAPATNA',' CPT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHANPATIA',' CAI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAPARMUKH JN',' CPK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHARANMAHADEVI',' SMD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAREGAON',' CRN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHARKHI DADRI',' CKD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHARLAPALLI',' CHZ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHARVATTUR',' CHV');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHATA',' CHJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHATRA',' CTR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHATRAPUR',' CAP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAU MAHLA',' CMU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAUK',' CHOK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAUKHANDI',' CHH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAUNRAH',' CNH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAURA',' CUX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAURI CHAURA',' CC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAUSA',' CSA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAUTARA',' CROA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAUTH KA BRWRA',' CKB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHAWAPALL',' CHA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHENGALPATTU',' CGL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHENGANNUR',' CNGR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHENNAI BEACH',' MSB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHENNAI CENTRAL',' MAS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHENNAI EGMORE',' MS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHEOKI',' COI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHERUKARA',' CQA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHETTINAD',' CTND');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHHABRA GUGOR',' CAG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHHANERA',' CAER');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHHAPI',' CHP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHHAPRA',' CPR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHHAPRA KACHERI',' CI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHHARODI',' CE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHHATNA',' CJN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHHINDWARA JN',' CWA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHHIPADOHAR',' CPDR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHHULHA',' CLF');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHIDAMBARAM',' CDM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHIHERU',' CEU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHIKHLI',' CKHS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHIKJAJUR JN',' JRU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHIKNI ROAD',' CKNI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHIKODI ROAD',' CKR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHILAKALAPUDI',' CLU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHILBILA JN',' CIL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHILIKIDARA',' CLDR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHILKA',' CLKA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHILKAHAR',' CHR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHIMA PAHAD',' CMW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHINCHLI',' CNC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHINCHVAD',' CCH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHINNA GANJAM',' CJM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHINNA SALEM',' CHSM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHIPLUN',' CHI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHIPURUPALLE',' CPP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHIRALA',' CLX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHIRAYINKIL',' CRY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHIRGAON',' CGN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHIRMIRI',' CHRM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHIT BARAGAON',' CBN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHITRAKOT',' CKTD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHITROD',' COE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHITTAPUR',' CT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHITTARANJAN',' CRJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHITTAURGARH',' COR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHITTOOR',' CTO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHITYALA',' CTYL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHOLA',' CHL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHOPAN',' CPU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHORVAD ROAD',' CVR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHOTI KHATU',' CTKT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHUCHURA',' CNS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHUNAR',' CAR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHURAIBARI',' CBZ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHURK',' CUK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CHURU',' CUR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CINNAMARA',' CMA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('COIMBATORE JN',' CBE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('COIMBATORE NRTH',' CBF');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('COLONELGANJ',' CLJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CUDDALORE PORT',' CUPJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CUDDAPAH',' HX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CUMBUM',' CBM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('CUTTACK',' CTC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DABHAURA',' DBR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DABRA',' DBA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DABTARA',' DUB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DADAR',' DDR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DADRI',' DER');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAHANU ROAD',' DRD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAHOD',' DHD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAKANIYA TALAV',' DKNT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAKHINESWAR',' DAKE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DALADI',' DL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DALAUDA',' DLD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DALBHUMGARH',' DVM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DALELNAGAR',' DLQ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DALGAON',' DLO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DALIGANJ',' DAL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DALKOLHA',' DLK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DALLI RAJHARA',' DRZ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DALMAU JN',' DMW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DALSINGH SARAI',' DSS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DALTONGANJ',' DTO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAMANJODI',' DMNJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAMCHARA',' DCA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAMOH',' DMO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DANAPUR',' DNR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DANAULI PHLWRIA',' DPL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DANDUPUR',' DND');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DANEA',' DNEA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DANGOAPOSI',' DPS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DANIYAWAN BZR H',' DNWH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DANTAN',' DNT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAOTUHAJA',' DJA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAPODI',' DAPD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAPPAR',' DHPR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DARA',' DARA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DARBHANGA JN',' DBG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DARJEELING',' DJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DARRITOLA',' DTL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DARYABAD',' DYD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DASHARATHPUR',' DRTP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DASUYA',' DZA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DATIA',' DAA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAUDPUR',' DDP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAULATABAD',' DLB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAULATPUR HAT',' DLPH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAUND JN',' DD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAURALA',' DRLA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAUSA',' DO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DAVANGERE',' DVG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEBAGRAM',' DEB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEGANA JN',' DNA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEHRADUN',' DDN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEHRI ON SONE',' DOS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEHU ROAD',' DEHR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DELANG',' DEG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DELHI',' DLI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DELHI CANTT',' DEC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DELHI KISHANGNJ',' DKZ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DELHI S ROHILLA',' DEE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DELHI SAFDARJNG',' DSJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DELHI SHAHDARA',' DSA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEOBAND',' DBD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEOGHAR',' DGHR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEORI',' DOE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEORIA SADAR',' DEOS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEOTALA',' DOTL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEPUR PH',' DPUR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEROL',' DRL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DESARI',' DES');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DESHNOK',' DSO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEVAKOTTAI ROAD',' DKO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEVBALODA CHRDA',' DBEC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEVLALI',' DVL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEWANGANJ',' DWG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DEWAS',' DWX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHABAN',' DABN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHACA CANTT',' DHCA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHALGAON',' DLGN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHAMALGAON',' DMGN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHAMANGAON',' DMN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHAMARA GHAT',' DHT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHAMPUR',' DPR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHANAURI',' DNRE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHANBAD JN',' DHN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHANDARI KALAN',' DDL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHANERA',' DQN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHANMANDAL',' DNM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHANSU',' DNX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHANUVACHAPURAM',' DAVM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHARANGAON',' DXG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHARHARA',' DRH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHARIWAL',' DHW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHARMABAD',' DAB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHARMANAGAR',' DMR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHARMAPURI',' DPJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHARMAVARAM JN',' DMM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHARMPUR HMCHL',' DMP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHARWAR',' DWR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHASA JN',' DAS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHAULPUR',' DHO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHAUNI',' DWLE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHAURA',' DUA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHEENA',' DHA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHEMAJI',' DMC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHENKANAL',' DNKL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHILWAN',' DIW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHIRERA',' DHRR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHODHAR',' DOD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHODRA MOHAR',' DOH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHOLA JN',' DLJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHOLI',' DOL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHONE',' DHNE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHORAJI',' DJI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHRANGDHRA',' DHG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHUBRI',' DBB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHULE',' DHI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHULIAN GANGA',' DGLE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHULKOT',' DKT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHUPGURI',' DQG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHURI JN',' DUI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DHURWASIN',' DRSN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DIBRUGARH',' DBRG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DIBRUGARH TOWN',' DBRT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DIDWANA',' DIA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DIGARU',' DGU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DIGBOI',' DBY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DIGHA FLAG STN',' DGHA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DIGHWARA',' DGA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DIHAKHO',' DKE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DILAWARNAGAR',' DIL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DILDARNAGAR JN',' DLN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DIMAPUR',' DMV');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DINA NAGAR',' DNN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DINDIGUL JN',' DG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DIPHU',' DPU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DISA',' DISA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DITOKCHERRA',' DTC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DIVINE NAGAR',' DINR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DIYODAR',' DEOR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DODBALLAPUR',' DBU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DOIWALA',' DWO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DOMINGARH',' DMG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DONAKONDA',' DKD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DONDAICHA',' DDE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DONGARGARH',' DGG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DORAHA',' DOA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DORNAKAL JN',' DKJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUBAHA',' DUBH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUBRAJPUR',' DUJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUDDHINAGAR',' DXN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUDHANI',' DUD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUGGIRALA',' DIG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DULIAJAN',' DJG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DULLAHAPUR',' DLR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUMKA',' DUMK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUMRAON',' DURE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUMRI BIHAR',' DMBR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUMRI HALT',' DMRX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUMURIPUT',' DMRT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUNDI',' DDCE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUNGARPUR',' DNRP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUNGRI',' DGI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DURAUNDHA JN',' DDA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DURG',' DURG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DURGAPUR',' DGR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DURGAPURA',' DPA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DURGAUTI',' DGO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUSI',' DUSI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DUVVADA',' DVD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DWARAPUDI',' DWP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('DWARKA',' DWK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('EKAMBARAKUPPAM',' EKM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('EKANGARSARAI',' EKR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('EKCHARI',' EKC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('EKLAKHI',' EKI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('EKMA',' EKMA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ELIMALA',' ELM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ELLAMANCHILI',' YLM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ELURU',' EE');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ERANAKULAM JN',' ERS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ERANIEL',' ERL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ERNAKULAM TOWN',' ERN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ERODE JN',' ED');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ERRUPALEM',' YP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ETAWAH',' ETW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ETTAPUR ROAD',' ETP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('ETTUMANUR',' ETM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FAIZABAD JN',' FD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FAIZULLAPUR',' FYZ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FAKIRAGRAM JN',' FKM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FALAKATA',' FLK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FALNA',' FA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FARAH TOWN',' FHT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FARIDABAD',' FDB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FARIDABAD NW TN',' FDN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FARIDKOT',' FDK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FARRUKHABAD',' FBD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FATEH SINGHPURA',' FSP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FATEHGARH',' FGR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FATEHGARH SAHIB',' FGSB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FATEHNAGAR',' FAN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FATEHPUR',' FTP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FATEHPUR SIKRI',' FTS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FATWA',' FUT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FEROK',' FK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FIROZABAD',' FZD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FIROZPUR CANT',' FZR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FORBESGANJ',' FBG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FURKATING JN',' FKG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('FURSATGANJ',' FTG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('G.RAMACHANDRAPU',' GRCP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GACHHIPURA',' GCH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GADAG JN',' GDG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GADARWARA',' GAR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GADWAL',' GWD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GAHMAR',' GMR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GAJRAULA JN',' GJL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GALGALIA',' GAGA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GALUDIH',' GUD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GAMHARIA',' GMH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANAGAPUR ROAD',' GUR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANAUR',' GNU');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANDHIDHAM BG',' GIMB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANDHINAGAR CAP',' GNC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANDHINAGAR JPR',' GADJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANESHGANJ',' GAJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANGADHARPUR',' GNGD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANGAGANJ',' GANG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANGAKHER',' GNH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANGAPUR CITY',' GGC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANGARAMPUR',' GRMP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANGIWARA',' GNW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANGRAR',' GGR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANGSAR JAITU',' GJUT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANJ BASODA',' BAQ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANJ DUNDWARA',' GWA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GANJAM',' GAM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GARH JAIPUR',' GUG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GARHBETA',' GBA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GARHI HARSARU',' GHH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GARHI MANIKPUR',' GRMR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GARHMUKTESAR',' GMS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GARHWA',' GHQ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GARIVIDI',' GVI');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GARLA',' GLA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GAROT',' GOH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GARPOS',' GPH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GARWA ROAD',' GHD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GAURA',' GRX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GAURI BAZAR',' GB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GAURIBIDANUR',' GBD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GAURIGANJ',' GNG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GAUSHALA',' GWS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GAUTAMSTHAN',' GTST');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GAYA JN',' GAYA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GAZOLE',' GZO');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GETOR JAGATPURA',' GTJT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GEVRA ROAD',' GAD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHAGWAL',' GHGL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHANAULI',' GANL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHANPUR',' GNP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHARAUNDA',' GRA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHATAMPUR',' GTM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHATERA',' GEA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHATPRABHA',' GPB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHATSILA',' GTS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHAZIABAD',' GZB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHAZIPUR CITY',' GCT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHOGA',' GGA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHOKSADANGA',' GDX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHOLVAD',' GVD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHONSOR',' GNS');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHORADONGRI',' GDYA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHORPURI',' GPR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHUGHULI',' GH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHUM',' GHUM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHUNGHUTI',' GGT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GHUTKU',' GTK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GIDDALUR',' GID');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GIDDARBAHA',' GDB');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GIDHAUR',' GHR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GILL',' GILL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GIRIDIH',' GRD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GIRIMAIDAN',' GMDN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GIRWAR',' GW');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOALDIH',' GADH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOALPARA TOWN',' GLPT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GODAVARI',' GVN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GODHRA JN',' GDA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOGAMUKH',' GOM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOHAD ROAD',' GOA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOHPUR',' GPZ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOILKERA',' GOL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOKAK ROAD',' GKK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOKARNA ROAD',' GOK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOLA GOKARANATH',' GK');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOLAGHAT',' GLGT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOLAKGANJ JN',' GKJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOLDINGANJ',' GJH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOLLAPROLU',' GLP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOMATI NAGAR',' GTNR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOMTA',' GTT');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GONDA JN',' GD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GONDAL',' GDL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GONDIA JN',' G');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GONDWANAVISAPUR',' GNVR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GONEANA',' GNA');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOOTY',' GY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOP JAM',' GOP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GORAKHNATH',' GRKN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GORAKHPUR CANT',' GKC');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GORAKHPUR JN',' GKP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GORAUL',' GRL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GORAYA',' GRY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOSALPUR',' GSPR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOSHAINGANJ',' GGJ');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOSSAIGAON HAT',' GOGH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOTAN',' GOTN');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOVINDGARH',' GVG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOVINDPUR ROAD',' GBX');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOVINDPURI',' GOY');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GOWDAVALLI',' GWV');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GUDIVADA JN',' GDV');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GUDIYATTAM',' GYM');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GUDLAVALLERU',' GVL');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GUDUR JN',' GDR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GUJHANDI',' GJD');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GULABHGANJ',' GLG');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GULABPURA',' GBP');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GULAOTHI',' GLH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GULBARGA',' GR');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GULDHAR',' GUH');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GULEDAGUDDA RD',' GED');
INSERT INTO `` (`Station_Name`,`Station_code`) VALUES ('GULZARBAGH',' GZH');
