# Stations
import mysql.connector
def station():
    Station = mysql.connector.connect(host="localhost", user="root", passwd="Kartikey30", database="ProjectRailway")
    C1 = Station.cursor()
    EnterStation = "insert into Station (Station_Name,Station_code) values(%s,%s)"
    StationName = [("A N DEV NAGAR "," ACND"),
("ABHAIPUR "," AHA"),
("ABOHAR "," ABS"),
("ABU ROAD "," ABR"),
("ACHALDA "," ULD"),
("ACHHNERA JN "," AH"),
("ADAVALI "," ADVI"),
("ADESAR "," AAR"),
("ADHARTAL "," ADTL"),
("ADILABAD "," ADB"),
("ADINA "," ADF"),
("ADIPUR "," AI"),
("ADITYAPUR "," ADTP"),
("ADONI "," AD"),
("ADRA JN "," ADRA"),
("ADRSH NGR DELHI "," ANDI"),
("ADUTURAI "," ADT"),
("AGARTALA "," AGTL"),
("AGORI KHAS "," AGY"),
("AGRA CANTT "," AGC"),
("AGRA CITY "," AGA"),
("AGRA FORT "," AF"),
("AHMADGARH "," AHH"),
("AHMADNAGAR "," ANG"),
("AHMADPUR JN "," AMP"),
("AHMEDABAD JN "," ADI"),
("AHRAURA ROAD "," ARW"),
("AISHBAGH "," ASH"),
("AIT "," AIT"),
("AITHAL "," ATMO"),
("AJMER JN "," AII"),
("AJNI "," AJNI"),
("AKALKOT ROAD "," AKOR"),
("AKALTARA "," AKT"),
("AKANAPET "," AKE"),
("AKBARGANJ "," AKJ"),
("AKBARNAGAR "," AKN"),
("AKBARPUR "," ABP"),
("AKIVIDU "," AKVD"),
("AKODIA "," AKD"),
("AKOLA JN "," AK"),
("AKSHAYWAT R NGR "," AYRN"),
("AKURDI "," AKRD"),
("alai "," ALJ"),
("ALAMNAGAR "," AMG"),
("ALAMPUR "," ALMR"),
("ALER "," ALER"),
("ALGAWAN "," AIG"),
("ALIA BADA "," ALB"),
("ALIGARH JN "," ALJN"),
("ALIPUR DUAR JN "," APDJ"),
("ALLAHABAD CITY "," ALY"),
("ALLAHABAD JN "," ALD"),
("ALLEPPEY "," ALLP"),
("ALMATTI "," LMT"),
("ALNAVAR JN "," LWR"),
("ALUABARI ROAD "," AUB"),
("ALUVA "," AWY"),
("ALWAR "," AWR"),
("AMALNER "," AN"),
("AMALSAD "," AML"),
("AMARDA ROAD "," ARD"),
("AMARGARH "," AGR"),
("AMB ANDAURA "," AADR"),
("AMBALA CANT JN "," UMB"),
("AMBALA CITY "," UBC"),
("AMBALAPUZHA "," AMPA"),
("AMBALE "," ABLE"),
("AMBARI FALAKATA "," ABFC"),
("AMBARNATH "," ABH"),
("AMBASA "," ABSA"),
("AMBASAMUDRAM "," ASD"),
("AMBATURAI "," ABI"),
("AMBIKA KALNA "," ABKA"),
("AMBIKAPUR "," ABKP"),
("AMBLI ROAD "," ABD"),
("AMBODALA "," AMB"),
("AMBUR "," AB"),
("AMDARA "," UDR"),
("AMETHI "," AME"),
("AMGAON "," AGN"),
("AMGURI "," AGI"),
("AMLA JN "," AMLA"),
("AMLAI "," AAL"),
("AMMANABROLU "," ANB"),
("AMMASANDRA "," AMSA"),
("AMONI "," AONI"),
("AMRAVATI "," AMI"),
("AMRITSAR JN "," ASR"),
("AMROHA "," AMRO"),
("ANAKAPALLE "," AKP"),
("ANAND JN "," ANND"),
("ANAND NAGAR "," ANDN"),
("ANAND VIHAR "," ANVR"),
("ANAND VIHAR TRM "," ANVT"),
("ANANDAPURAM "," ANF"),
("ANANDPUR SAHIB "," ANSB"),
("ANANTAPUR "," ATP"),
("ANAPARTI "," APT"),
("ANARA "," ANR"),
("ANAS "," ANAS"),
("ANAVARDIKHANPET "," AVN"),
("ANDAL JN "," UDL"),
("ANDHERI "," ADH"),
("ANGADIPPURAM "," AAM"),
("ANGAMALI "," AFK"),
("ANGUL "," ANGL"),
("ANJAR "," AJE"),
("ANJHI SHAHABAD "," AJI"),
("ANKAI "," ANK"),
("ANKLESHWAR JN "," AKV"),
("ANKOLA "," ANKL"),
("ANKORAH AKORHA "," ANH"),
("ANNAVARAM "," ANV"),
("ANNIGERI "," NGR"),
("ANPARA "," ANPR"),
("ANTAH "," ATH"),
("ANTU "," ANTU"),
("ANUGRAHA N ROAD "," AUBR"),
("ANUPPUR JN "," APR"),
("AONLA "," AO"),
("ARA "," ARA"),
("ARAG "," ARAG"),
("ARAKKONAM "," AJJ"),
("ARALVAYMOZHI "," AAY"),
("ARARIYA COURT "," ARQ"),
("ARAVALI ROAD "," AVRD"),
("ARIGADA "," ARGD"),
("ARIYALUR "," ALU"),
("ARJUNI "," AJU"),
("ARNI ROAD "," ARV"),
("ARSIKERE JN "," ASK"),
("ARUMUGANERI "," ANY"),
("ARUNACHAL "," ARCL"),
("ASAFPUR "," AFR"),
("ASALPUR JOBNER "," JOB"),
("ASANSOL JN "," ASN"),
("ASAOTI "," AST"),
("ASARVA JN "," ASV"),
("ASHAPURA GOMAT "," AQG"),
("ASHOK NAGAR "," ASKN"),
("ASIFABAD ROAD "," ASAF"),
("ASLANA "," ANA"),
("ASRANADA "," AAS"),
("ATARI "," ATT"),
("ATARRA "," ATE"),
("ATHMAL GOLA "," ATL"),
("ATTABIRA "," ATS"),
("ATTILI "," AL"),
("ATTUR "," ATU"),
("AUNG "," AUNG"),
("AUNRIHAR JN "," ARJ"),
("AURANGABAD "," AWB"),
("AVADI "," AVD"),
("AWATARNAGAR "," ATNR"),
("AYODHYA "," AY"),
("AYODHYAPATTANAM "," APN"),
("AZAMGARH "," AMH"),
("AZAMNAGAR ROAD "," AZR"),
("AZIMGANJ JN "," AZ"),
("B CEMENT NAGAR "," BEY"),
("BABATPUR "," BTP"),
("BABHNAN "," BV"),
("BABINA "," BAB"),
("BABRALA "," BBA"),
("BABUPETH "," BUPH"),
("BACHHRAWAN "," BCN"),
("BACHWARA JN "," BCA"),
("BADABANDHA "," BDBA"),
("BADAMI "," BDM"),
("BADARPUR JN "," BPB"),
("BADARWAS "," BDWS"),
("BADHWA BARA "," BDWA"),
("BADLA GHAT "," BHB"),
("BADLAPUR "," BUD"),
("BADLI "," BHD"),
("BADMAL "," BUDM"),
("BADNAPUR "," BDU"),
("BADNERA JN "," BD"),
("BADODAR "," BDDR"),
("BADSHAHNAGAR "," BNZ"),
("BADSHAHPUR "," BSE"),
("BADULIPAR "," BLPR"),
("BAGAHA "," BUG"),
("BAGALKOT "," BGK"),
("BAGBAHRA "," BGBR"),
("BAGDIHI "," BEH"),
("BAGETAR "," BF"),
("BAGEVADI RD "," BSRX"),
("BAGHAULI "," BGH"),
("BAGHDOGRA "," BORA"),
("BAGHORA "," BJQ"),
("BAGHUAPAL "," BGPL"),
("BAGNAN "," BZN"),
("BAGRA TAWA "," BGTA"),
("BAHADUR SINGH W "," BSS"),
("BAHADURGARH "," BGZ"),
("BAHJOI "," BJ"),
("BAHRAICH "," BRK"),
("BAIDYANATHDHAM "," BDME"),
("BAIGUDA "," BGUA"),
("BAIHATOLA "," BATL"),
("BAIKUNTHPUR RD "," BRH"),
("BAIRAGARH "," BIH"),
("BAITARANI ROAD "," BTV"),
("BAJUD "," BJUD"),
("BAJVA "," BJW"),
("BAKHLETA "," BQQ"),
("BAKHTIYARPUR JN "," BKP"),
("BALAGHAT JN "," BTC"),
("BALAMU JN "," BLM"),
("BALANGIR "," BLGR"),
("BALASORE "," BLS"),
("BALAWALI "," BLW"),
("BALHARSHAH "," BPQ"),
("BALLABGARH "," BVH"),
("BALLIA "," BUI"),
("BALOD "," BXA"),
("BALOTRA JN "," BLT"),
("BALPUR HALT "," BPRH"),
("BALUGAN "," BALU"),
("BALURGHAT "," BLGT"),
("BAMHRAULI "," BMU"),
("BAMLA "," BMLL"),
("BAMNIA "," BMI"),
("BAMRA "," BMB"),
("BANAHI "," BYN"),
("BANAPURA "," BPF"),
("BANAR "," BNO"),
("BANASWADI "," BAND"),
("BANBASA "," BNSA"),
("BANDA JN "," BNDA"),
("BANDAKPUR "," BNU"),
("BANDANWARA "," BDW"),
("BANDARKHAL "," BXK"),
("BANDEL JN "," BDC"),
("BANDIKUI JN "," BKI"),
("BANDRA TERMINUS "," BDTS"),
("BANGALORE CANT "," BNC"),
("BANGALORE CY JN "," SBC"),
("BANGALORE EAST "," BNCE"),
("BANGARAPET "," BWT"),
("BANGRIPOSI "," BGY"),
("BANGROD "," BOD"),
("BANI "," BANI"),
("BANKA "," BAKA"),
("BANKA GHAT "," BKG"),
("BANKATA "," BTK"),
("BANKHEDI "," BKH"),
("BANKURA "," BQA"),
("BANMOR "," BAO"),
("BANO "," BANO"),
("BANSIPUR "," BSQP"),
("BANSPANI "," BSPX"),
("BANSTHALI NIWAI "," BNLW"),
("BANTAWALA "," BNTL"),
("BANTHRA "," BTRA"),
("BAPATLA "," BPP"),
("BAPUDM MOTIHARI "," BMKI"),
("BARA JAMDA "," BJMD"),
("BARABANKI JN "," BBK"),
("BARABHUM "," BBM"),
("BARABIL "," BBN"),
("BARADWAR "," BUA"),
("BARAGOPAL "," BAGL"),
("BARAHAT "," BHLE"),
("BARAIGRAM JN "," BRGM"),
("BARAKAR "," BRR"),
("BARAL "," BARL"),
("BARAN "," BAZ"),
("BARANG "," BRAG"),
("BARARA "," RAA"),
("BARAUNI JN "," BJU"),
("BARAUT "," BTU"),
("BARBATPUR "," BBTR"),
("BARCHI ROAD "," BCRD"),
("BARDDHAMAN JN "," BWN"),
("BARDOLI "," BIY"),
("BAREILLY "," BE"),
("BAREILLY CITY "," BC"),
("BAREJADI "," BJD"),
("BARELIPUR "," BQM"),
("BARETA "," BRZ"),
("BARETH "," BET"),
("BARGARH "," BRG"),
("BARGARH ROAD "," BRGA"),
("BARGAWAN "," BRGW"),
("BARGI "," BUQ"),
("BARH "," BARH"),
("BARHARWA JN "," BHW"),
("BARHIYA "," BRYA"),
("BARHNI "," BNY"),
("BARI BRAHMAN "," BBMN"),
("BARIARPUR "," BUP"),
("BARIPADA "," BPO"),
("BARKA KANA "," BRKA"),
("BARKHERA "," BKA"),
("BARKISALALYA "," BSYA"),
("BARKUR "," BKJ"),
("BARLAI "," BLAX"),
("BARMER "," BME"),
("BARNALA "," BNN"),
("BAROG "," BOF"),
("BARPALI "," BRPL"),
("BARPATHAR "," BXP"),
("BARPETA ROAD "," BPRD"),
("BARRACKPORE "," BP"),
("BARRAJPUR "," BJR"),
("BARSALI "," BYS"),
("BARSI TOWN "," BTW"),
("BARSOI JN "," BOE"),
("BARSOLA "," BZO"),
("BARUA BAMUNGAON "," BBGN"),
("BARUD "," BRUD"),
("BARWA SAGAR "," BWR"),
("BARWADIH JN "," BRWD"),
("BARWALA "," BXC"),
("BASAI "," BZY"),
("BASANTAPUR "," BSTP"),
("BASAR "," BSX"),
("BASBARI "," BSI"),
("BASHARATGANJ "," BTG"),
("BASMAT "," BMF"),
("BASNI "," BANE"),
("BASSI "," BAI"),
("BASSI PATHANAM "," BSPN"),
("BASTA "," BTS"),
("BASTI "," BST"),
("BASUGAON "," BSGN"),
("BASUKINATH "," BSKH"),
("BASWA "," BU"),
("BATALA JN "," BAT"),
("BAWAL "," BWL"),
("BAYANA JN "," BXN"),
("BAYTU "," BUT"),
("BAZARSAU "," BZLE"),
("BEAS "," BEAS"),
("BEAWAR "," BER"),
("BEGAMPET "," BMT"),
("BEGU SARAI "," BGS"),
("BEHTAGOKUL "," BEG"),
("BEKAL FORT "," BFR"),
("BELA "," BELA"),
("BELA TAL "," BTX"),
("BELAKOBA "," BLK"),
("BELAMPALLI "," BPA"),
("BELAPUR "," BAP"),
("BELDA "," BLDA"),
("BELDANGA "," BEB"),
("BELGAHNA "," BIG"),
("BELGAUM "," BGM"),
("BELHA "," BYL"),
("BELLARY JN "," BAY"),
("BELPAHAR "," BPH"),
("BELRAYAN "," BXM"),
("BELTHARA ROAD "," BLTR"),
("BEOHARI "," BEHR"),
("BERCHHA "," BCH"),
("BERHAMPORE CRT "," BPC"),
("BERMO "," BRMO"),
("BETAMCHERLA "," BMH"),
("BETHAMPURDI "," BTPD"),
("BETHUADAHARI "," BTY"),
("BETNOTI "," BTQ"),
("BETTIAH "," BTH"),
("BETUL "," BZU"),
("BHABHAR "," BAH"),
("BHABUA ROAD "," BBU"),
("BHACHAU BG "," BCOB"),
("BHADAN "," BDN"),
("BHADAURA "," BWH"),
("BHADOHI "," BOY"),
("BHADRACHALAM RD "," BDCR"),
("BHADRAK "," BHC"),
("BHADRAVATI "," BDVT"),
("BHAGA JN "," VAA"),
("BHAGALPUR "," BGP"),
("BHAGAT KI KOTHI "," BGKT"),
("BHAGWANGOLA "," BQG"),
("BHAGWANPUR "," BNR"),
("BHAIROGANJ "," BRU"),
("BHAIRONGARH "," BOG"),
("BHAKTI NAGAR "," BKNG"),
("BHALKI "," BHLK"),
("BHALUI "," BFM"),
("BHALUKA ROAD F "," BKRD"),
("BHALUKMARA "," BLMR"),
("BHALUMASKA "," BLMK"),
("BHANAPUR "," BNP"),
("BHANDAK "," BUX"),
("BHANDARA ROAD "," BRD"),
("BHANDARIDAH "," BHME"),
("BHANVAD "," BNVD"),
("BHANWAR TONK "," BHTK"),
("BHARAT KUP "," BTKP"),
("BHARATPUR JN "," BTE"),
("BHARTHANA "," BNT"),
("BHARUCH JN "," BH"),
("BHARWA SUMERPUR "," BSZ"),
("BHARWARI "," BRE"),
("BHATAPARA "," BYT"),
("BHATINDA JN "," BTI"),
("BHATIYA "," BHTA"),
("BHATKAL "," BTJL"),
("BHATNI JN "," BTT"),
("BHATPAR RANI "," BHTR"),
("BHATTU "," BHT"),
("BHAVANAGAR PARA "," BVP"),
("BHAVANI NAGAR "," BVNR"),
("BHAVNAGAR TRMUS "," BVC"),
("BHAWANI MANDI "," BWM"),
("BHAWANIPATNA "," BWIP"),
("BHAYAVADAR "," BHY"),
("BHEDIA "," BDH"),
("BHERAGHAT "," BRGT"),
("BHIGWAN "," BGVN"),
("BHILAD "," BLD"),
("BHILAI "," BIA"),
("BHILAI PWR HS "," BPHB"),
("BHILAINAGAR "," BQR"),
("BHILAVDI "," BVQ"),
("BHILDI "," BLDI"),
("BHILWARA "," BHL"),
("BHIMADOLU "," BMD"),
("BHIMASAR BG "," BMSB"),
("BHIMAVARAM JN "," BVRM"),
("BHIMAVARAM TOWN "," BVRT"),
("BHIMSEN "," BZM"),
("BHIND "," BIX"),
("BHIRA KHERI "," BIK"),
("BHITONI "," BHTN"),
("BHIWANDI ROAD "," BIRD"),
("BHIWANI "," BNW"),
("BHIWANI CITY "," BNWC"),
("BHOJIPURA JN "," BPR"),
("BHOJO "," BOJ"),
("BHOJUDIH JN "," BJE"),
("BHOKAR "," BOKR"),
("BHONGAON "," BGQ"),
("BHONGIR "," BG"),
("BHOPAL JN "," BPL"),
("BHORAS BUDRUKH "," BFJ"),
("BHUBANESWAR "," BBS"),
("BHUCHCHU "," BCU"),
("BHUGAON "," BPK"),
("BHUJ "," BHUJ"),
("BHULANPUR "," BHLP"),
("BHUPIA MAU "," VPO"),
("BHURKUNDA "," BHKD"),
("BHUSANDPUR "," BSDP"),
("BHUSAVAL JN "," BSL"),
("BIBINAGAR "," BN"),
("BICHIA "," BIC"),
("BIDADI "," BID"),
("BIDAR "," BIDR"),
("BIDHAN NAGAR "," BNXR"),
("BIGHAPUR "," BQP"),
("BIHAR SHARIF "," BEHS"),
("BIHARA "," BHZ"),
("BIHIYA "," BEA"),
("BIHTA "," BTA"),
("BIJAINAGAR "," BJNR"),
("BIJAPUR "," BJP"),
("BIJAYSOTA "," VST"),
("BIJNI "," BJF"),
("BIJNOR "," BJO"),
("BIJOOR "," BIJR"),
("BIJURI "," BJRI"),
("BIJWASAN "," BWSN"),
("BIKANER JN "," BKN"),
("BIKKAVOLU "," BVL"),
("BIKRAM SHILA "," BKSL"),
("BIKRAMPUR "," BMR"),
("BILASPUR JN "," BSP"),
("BILASPUR ROAD "," BLQR"),
("BILDI "," BILD"),
("BILGA "," BZG"),
("BILHAR GHAT "," BLG"),
("BILHAUR "," BLU"),
("BILIMORA JN "," BIM"),
("BILPUR "," BLPU"),
("BILWAI "," BWI"),
("BINA JN "," BINA"),
("BINDKI ROAD "," BKO"),
("BINNAGURI "," BNV"),
("BIRADHWAL "," BDWL"),
("BIRAPATTI "," BRPT"),
("BIRSINGHPUR "," BRS"),
("BIRUR JN "," RRB"),
("BISHNATHGANJ "," BTJ"),
("BISHNUPUR "," VSU"),
("BISHRAMPUR "," BSPR"),
("BISRA "," BZR"),
("BISSAMCUTTACK "," BMCK"),
("BISUGIRSHARIF "," BGSF"),
("BISWAN "," BVN"),
("BITRAGUNTA "," BTTR"),
("BIYAVRA RAJGARH "," BRRG"),
("BOBBILI "," VBL"),
("BODHADI BUJRUG "," BHBK"),
("BODWAD "," BDWD"),
("BOHALI "," BHLI"),
("BOHANI "," BNE"),
("BOINDA "," BONA"),
("BOISAR "," BOR"),
("BOKAJAN "," BXJ"),
("BOKARO STL CITY "," BKSC"),
("BOKARO THERMAL "," BKRO"),
("BOLARUM "," BMO"),
("BOLINNA DOABA "," BLND"),
("BOLPUR S NIKTN "," BHP"),
("BOMMIDI "," BQI"),
("BONA KALU "," BKL"),
("BONDAMUNDA "," BNDM"),
("BONGAIGAON "," BNGN"),
("BORDHAL "," BXY"),
("BORDI "," BIO"),
("BORHAT "," BFD"),
("BORIDAND "," BRND"),
("BORIVALI "," BVI"),
("BORVIHIR "," BRVR"),
("BOTAD JN "," BTD"),
("BRAHMAPUR "," BAM"),
("BRAJRAJNAGAR "," BRJN"),
("BUDALUR "," BAL"),
("BUDAUN "," BEM"),
("BUDDIREDDIPPATI "," BDY"),
("BUDHI "," BDHY"),
("BUDHLADA "," BLZ"),
("BUDNI "," BNI"),
("BUDVEL "," BDVL"),
("BULANDSHAHR "," BSC"),
("BUNDI "," BUDI"),
("BUNIADPUR "," BNDP"),
("BURHANPUR "," BAU"),
("BURHAR "," BUH"),
("BURHWAL "," BUW"),
("BURNPUR "," BURN"),
("BUTARI "," BTR"),
("BUTI BORI "," BTBR"),
("BUXAR "," BXR"),
("BYADGI "," BYD"),
("C SHAHUMHARAJ T "," KOP"),
("CANCONA "," CNO"),
("CARMELARAM "," CRLM"),
("CASTLE ROCK "," CLR"),
("CHABUA "," CHB"),
("CHACHAURA BNGJ "," CBK"),
("CHAIBASA "," CBSA"),
("CHAINPUR "," CNPR"),
("CHAINWA "," CW"),
("CHAJLI "," CJL"),
("CHAKARPUR "," CKK"),
("CHAKDAYALA "," CKDL"),
("CHAKIA "," CAA"),
("CHAKKI BANK "," CHKB"),
("CHAKRADHARPUR "," CKP"),
("CHAKULIA "," CKU"),
("CHALAKUDI "," CKI"),
("CHALISGAON JN "," CSN"),
("CHAMPA "," CPH"),
("CHAMPANER RD JN "," CPN"),
("CHAND SIAU "," CPS"),
("CHANDA FORT "," CAF"),
("CHANDAN NAGAR "," CGR"),
("CHANDAULI MJHWR "," CDMR"),
("CHANDAUSI JN "," CH"),
("CHANDERIYA "," CNA"),
("CHANDI MANDIR "," CNDM"),
("CHANDIA ROAD "," CHD"),
("CHANDIGARH "," CDG"),
("CHANDIL JN "," CNI"),
("CHANDLODIYA "," CLDY"),
("CHANDOK "," CNK"),
("CHANDRAKONA RD "," CDGR"),
("CHANDRANATHPUR "," CNE"),
("CHANDRAPUR "," CD"),
("CHANDRAPURA "," CRP"),
("CHANDUR "," CND"),
("CHANDUR BAZAR "," CNDB"),
("CHANGANASERI "," CGY"),
("CHANNAPATNA "," CPT"),
("CHANPATIA "," CAI"),
("CHAPARMUKH JN "," CPK"),
("CHARANMAHADEVI "," SMD"),
("CHAREGAON "," CRN"),
("CHARKHI DADRI "," CKD"),
("CHARLAPALLI "," CHZ"),
("CHARVATTUR "," CHV"),
("CHATA "," CHJ"),
("CHATRA "," CTR"),
("CHATRAPUR "," CAP"),
("CHAU MAHLA "," CMU"),
("CHAUK "," CHOK"),
("CHAUKHANDI "," CHH"),
("CHAUNRAH "," CNH"),
("CHAURA "," CUX"),
("CHAURI CHAURA "," CC"),
("CHAUSA "," CSA"),
("CHAUTARA "," CROA"),
("CHAUTH KA BRWRA "," CKB"),
("CHAWAPALL "," CHA"),
("CHENGALPATTU "," CGL"),
("CHENGANNUR "," CNGR"),
("CHENNAI BEACH "," MSB"),
("CHENNAI CENTRAL "," MAS"),
("CHENNAI EGMORE "," MS"),
("CHEOKI "," COI"),
("CHERUKARA "," CQA"),
("CHETTINAD "," CTND"),
("CHHABRA GUGOR "," CAG"),
("CHHANERA "," CAER"),
("CHHAPI "," CHP"),
("CHHAPRA "," CPR"),
("CHHAPRA KACHERI "," CI"),
("CHHARODI "," CE"),
("CHHATNA "," CJN"),
("CHHINDWARA JN "," CWA"),
("CHHIPADOHAR "," CPDR"),
("CHHULHA "," CLF"),
("CHIDAMBARAM "," CDM"),
("CHIHERU "," CEU"),
("CHIKHLI "," CKHS"),
("CHIKJAJUR JN "," JRU"),
("CHIKNI ROAD "," CKNI"),
("CHIKODI ROAD "," CKR"),
("CHILAKALAPUDI "," CLU"),
("CHILBILA JN "," CIL"),
("CHILIKIDARA "," CLDR"),
("CHILKA "," CLKA"),
("CHILKAHAR "," CHR"),
("CHIMA PAHAD "," CMW"),
("CHINCHLI "," CNC"),
("CHINCHVAD "," CCH"),
("CHINNA GANJAM "," CJM"),
("CHINNA SALEM "," CHSM"),
("CHIPLUN "," CHI"),
("CHIPURUPALLE "," CPP"),
("CHIRALA "," CLX"),
("CHIRAYINKIL "," CRY"),
("CHIRGAON "," CGN"),
("CHIRMIRI "," CHRM"),
("CHIT BARAGAON "," CBN"),
("CHITRAKOT "," CKTD"),
("CHITROD "," COE"),
("CHITTAPUR "," CT"),
("CHITTARANJAN "," CRJ"),
("CHITTAURGARH "," COR"),
("CHITTOOR "," CTO"),
("CHITYALA "," CTYL"),
("CHOLA "," CHL"),
("CHOPAN "," CPU"),
("CHORVAD ROAD "," CVR"),
("CHOTI KHATU "," CTKT"),
("CHUCHURA "," CNS"),
("CHUNAR "," CAR"),
("CHURAIBARI "," CBZ"),
("CHURK "," CUK"),
("CHURU "," CUR"),
("CINNAMARA "," CMA"),
("COIMBATORE JN "," CBE"),
("COIMBATORE NRTH "," CBF"),
("COLONELGANJ "," CLJ"),
("CUDDALORE PORT "," CUPJ"),
("CUDDAPAH "," HX"),
("CUMBUM "," CBM"),
("CUTTACK "," CTC"),
("DABHAURA "," DBR"),
("DABRA "," DBA"),
("DABTARA "," DUB"),
("DADAR "," DDR"),
("DADRI "," DER"),
("DAHANU ROAD "," DRD"),
("DAHOD "," DHD"),
("DAKANIYA TALAV "," DKNT"),
("DAKHINESWAR "," DAKE"),
("DALADI "," DL"),
("DALAUDA "," DLD"),
("DALBHUMGARH "," DVM"),
("DALELNAGAR "," DLQ"),
("DALGAON "," DLO"),
("DALIGANJ "," DAL"),
("DALKOLHA "," DLK"),
("DALLI RAJHARA "," DRZ"),
("DALMAU JN "," DMW"),
("DALSINGH SARAI "," DSS"),
("DALTONGANJ "," DTO"),
("DAMANJODI "," DMNJ"),
("DAMCHARA "," DCA"),
("DAMOH "," DMO"),
("DANAPUR "," DNR"),
("DANAULI PHLWRIA "," DPL"),
("DANDUPUR "," DND"),
("DANEA "," DNEA"),
("DANGOAPOSI "," DPS"),
("DANIYAWAN BZR H "," DNWH"),
("DANTAN "," DNT"),
("DAOTUHAJA "," DJA"),
("DAPODI "," DAPD"),
("DAPPAR "," DHPR"),
("DARA "," DARA"),
("DARBHANGA JN "," DBG"),
("DARJEELING "," DJ"),
("DARRITOLA "," DTL"),
("DARYABAD "," DYD"),
("DASHARATHPUR "," DRTP"),
("DASUYA "," DZA"),
("DATIA "," DAA"),
("DAUDPUR "," DDP"),
("DAULATABAD "," DLB"),
("DAULATPUR HAT "," DLPH"),
("DAUND JN "," DD"),
("DAURALA "," DRLA"),
("DAUSA "," DO"),
("DAVANGERE "," DVG"),
("DEBAGRAM "," DEB"),
("DEGANA JN "," DNA"),
("DEHRADUN "," DDN"),
("DEHRI ON SONE "," DOS"),
("DEHU ROAD "," DEHR"),
("DELANG "," DEG"),
("DELHI "," DLI"),
("DELHI CANTT "," DEC"),
("DELHI KISHANGNJ "," DKZ"),
("DELHI S ROHILLA "," DEE"),
("DELHI SAFDARJNG "," DSJ"),
("DELHI SHAHDARA "," DSA"),
("DEOBAND "," DBD"),
("DEOGHAR "," DGHR"),
("DEORI "," DOE"),
("DEORIA SADAR "," DEOS"),
("DEOTALA "," DOTL"),
("DEPUR PH "," DPUR"),
("DEROL "," DRL"),
("DESARI "," DES"),
("DESHNOK "," DSO"),
("DEVAKOTTAI ROAD "," DKO"),
("DEVBALODA CHRDA "," DBEC"),
("DEVLALI "," DVL"),
("DEWANGANJ "," DWG"),
("DEWAS "," DWX"),
("DHABAN "," DABN"),
("DHACA CANTT "," DHCA"),
("DHALGAON "," DLGN"),
("DHAMALGAON "," DMGN"),
("DHAMANGAON "," DMN"),
("DHAMARA GHAT "," DHT"),
("DHAMPUR "," DPR"),
("DHANAURI "," DNRE"),
("DHANBAD JN "," DHN"),
("DHANDARI KALAN "," DDL"),
("DHANERA "," DQN"),
("DHANMANDAL "," DNM"),
("DHANSU "," DNX"),
("DHANUVACHAPURAM "," DAVM"),
("DHARANGAON "," DXG"),
("DHARHARA "," DRH"),
("DHARIWAL "," DHW"),
("DHARMABAD "," DAB"),
("DHARMANAGAR "," DMR"),
("DHARMAPURI "," DPJ"),
("DHARMAVARAM JN "," DMM"),
("DHARMPUR HMCHL "," DMP"),
("DHARWAR "," DWR"),
("DHASA JN "," DAS"),
("DHAULPUR "," DHO"),
("DHAUNI "," DWLE"),
("DHAURA "," DUA"),
("DHEENA "," DHA"),
("DHEMAJI "," DMC"),
("DHENKANAL "," DNKL"),
("DHILWAN "," DIW"),
("DHIRERA "," DHRR"),
("DHODHAR "," DOD"),
("DHODRA MOHAR "," DOH"),
("DHOLA JN "," DLJ"),
("DHOLI "," DOL"),
("DHONE "," DHNE"),
("DHORAJI "," DJI"),
("DHRANGDHRA "," DHG"),
("DHUBRI "," DBB"),
("DHULE "," DHI"),
("DHULIAN GANGA "," DGLE"),
("DHULKOT "," DKT"),
("DHUPGURI "," DQG"),
("DHURI JN "," DUI"),
("DHURWASIN "," DRSN"),
("DIBRUGARH "," DBRG"),
("DIBRUGARH TOWN "," DBRT"),
("DIDWANA "," DIA"),
("DIGARU "," DGU"),
("DIGBOI "," DBY"),
("DIGHA FLAG STN "," DGHA"),
("DIGHWARA "," DGA"),
("DIHAKHO "," DKE"),
("DILAWARNAGAR "," DIL"),
("DILDARNAGAR JN "," DLN"),
("DIMAPUR "," DMV"),
("DINA NAGAR "," DNN"),
("DINDIGUL JN "," DG"),
("DIPHU "," DPU"),
("DISA "," DISA"),
("DITOKCHERRA "," DTC"),
("DIVINE NAGAR "," DINR"),
("DIYODAR "," DEOR"),
("DODBALLAPUR "," DBU"),
("DOIWALA "," DWO"),
("DOMINGARH "," DMG"),
("DONAKONDA "," DKD"),
("DONDAICHA "," DDE"),
("DONGARGARH "," DGG"),
("DORAHA "," DOA"),
("DORNAKAL JN "," DKJ"),
("DUBAHA "," DUBH"),
("DUBRAJPUR "," DUJ"),
("DUDDHINAGAR "," DXN"),
("DUDHANI "," DUD"),
("DUGGIRALA "," DIG"),
("DULIAJAN "," DJG"),
("DULLAHAPUR "," DLR"),
("DUMKA "," DUMK"),
("DUMRAON "," DURE"),
("DUMRI BIHAR "," DMBR"),
("DUMRI HALT "," DMRX"),
("DUMURIPUT "," DMRT"),
("DUNDI "," DDCE"),
("DUNGARPUR "," DNRP"),
("DUNGRI "," DGI"),
("DURAUNDHA JN "," DDA"),
("DURG "," DURG"),
("DURGAPUR "," DGR"),
("DURGAPURA "," DPA"),
("DURGAUTI "," DGO"),
("DUSI "," DUSI"),
("DUVVADA "," DVD"),
("DWARAPUDI "," DWP"),
("DWARKA "," DWK"),
("EKAMBARAKUPPAM "," EKM"),
("EKANGARSARAI "," EKR"),
("EKCHARI "," EKC"),
("EKLAKHI "," EKI"),
("EKMA "," EKMA"),
("ELIMALA "," ELM"),
("ELLAMANCHILI "," YLM"),
("ELURU "," EE"),
("ERANAKULAM JN "," ERS"),
("ERANIEL "," ERL"),
("ERNAKULAM TOWN "," ERN"),
("ERODE JN "," ED"),
("ERRUPALEM "," YP"),
("ETAWAH "," ETW"),
("ETTAPUR ROAD "," ETP"),
("ETTUMANUR "," ETM"),
("FAIZABAD JN "," FD"),
("FAIZULLAPUR "," FYZ"),
("FAKIRAGRAM JN "," FKM"),
("FALAKATA "," FLK"),
("FALNA "," FA"),
("FARAH TOWN "," FHT"),
("FARIDABAD "," FDB"),
("FARIDABAD NW TN "," FDN"),
("FARIDKOT "," FDK"),
("FARRUKHABAD "," FBD"),
("FATEH SINGHPURA "," FSP"),
("FATEHGARH "," FGR"),
("FATEHGARH SAHIB "," FGSB"),
("FATEHNAGAR "," FAN"),
("FATEHPUR "," FTP"),
("FATEHPUR SIKRI "," FTS"),
("FATWA "," FUT"),
("FEROK "," FK"),
("FIROZABAD "," FZD"),
("FIROZPUR CANT "," FZR"),
("FORBESGANJ "," FBG"),
("FURKATING JN "," FKG"),
("FURSATGANJ "," FTG"),
("G.RAMACHANDRAPU "," GRCP"),
("GACHHIPURA "," GCH"),
("GADAG JN "," GDG"),
("GADARWARA "," GAR"),
("GADWAL "," GWD"),
("GAHMAR "," GMR"),
("GAJRAULA JN "," GJL"),
("GALGALIA "," GAGA"),
("GALUDIH "," GUD"),
("GAMHARIA "," GMH"),
("GANAGAPUR ROAD "," GUR"),
("GANAUR "," GNU"),
("GANDHIDHAM BG "," GIMB"),
("GANDHINAGAR CAP "," GNC"),
("GANDHINAGAR JPR "," GADJ"),
("GANESHGANJ "," GAJ"),
("GANGADHARPUR "," GNGD"),
("GANGAGANJ "," GANG"),
("GANGAKHER "," GNH"),
("GANGAPUR CITY "," GGC"),
("GANGARAMPUR "," GRMP"),
("GANGIWARA "," GNW"),
("GANGRAR "," GGR"),
("GANGSAR JAITU "," GJUT"),
("GANJ BASODA "," BAQ"),
("GANJ DUNDWARA "," GWA"),
("GANJAM "," GAM"),
("GARH JAIPUR "," GUG"),
("GARHBETA "," GBA"),
("GARHI HARSARU "," GHH"),
("GARHI MANIKPUR "," GRMR"),
("GARHMUKTESAR "," GMS"),
("GARHWA "," GHQ"),
("GARIVIDI "," GVI"),
("GARLA "," GLA"),
("GAROT "," GOH"),
("GARPOS "," GPH"),
("GARWA ROAD "," GHD"),
("GAURA "," GRX"),
("GAURI BAZAR "," GB"),
("GAURIBIDANUR "," GBD"),
("GAURIGANJ "," GNG"),
("GAUSHALA "," GWS"),
("GAUTAMSTHAN "," GTST"),
("GAYA JN "," GAYA"),
("GAZOLE "," GZO"),
("GETOR JAGATPURA "," GTJT"),
("GEVRA ROAD "," GAD"),
("GHAGWAL "," GHGL"),
("GHANAULI "," GANL"),
("GHANPUR "," GNP"),
("GHARAUNDA "," GRA"),
("GHATAMPUR "," GTM"),
("GHATERA "," GEA"),
("GHATPRABHA "," GPB"),
("GHATSILA "," GTS"),
("GHAZIABAD "," GZB"),
("GHAZIPUR CITY "," GCT"),
("GHOGA "," GGA"),
("GHOKSADANGA "," GDX"),
("GHOLVAD "," GVD"),
("GHONSOR "," GNS"),
("GHORADONGRI "," GDYA"),
("GHORPURI "," GPR"),
("GHUGHULI "," GH"),
("GHUM "," GHUM"),
("GHUNGHUTI "," GGT"),
("GHUTKU "," GTK"),
("GIDDALUR "," GID"),
("GIDDARBAHA "," GDB"),
("GIDHAUR "," GHR"),
("GILL "," GILL"),
("GIRIDIH "," GRD"),
("GIRIMAIDAN "," GMDN"),
("GIRWAR "," GW"),
("GOALDIH "," GADH"),
("GOALPARA TOWN "," GLPT"),
("GODAVARI "," GVN"),
("GODHRA JN "," GDA"),
("GOGAMUKH "," GOM"),
("GOHAD ROAD "," GOA"),
("GOHPUR "," GPZ"),
("GOILKERA "," GOL"),
("GOKAK ROAD "," GKK"),
("GOKARNA ROAD "," GOK"),
("GOLA GOKARANATH "," GK"),
("GOLAGHAT "," GLGT"),
("GOLAKGANJ JN "," GKJ"),
("GOLDINGANJ "," GJH"),
("GOLLAPROLU "," GLP"),
("GOMATI NAGAR "," GTNR"),
("GOMTA "," GTT"),
("GONDA JN "," GD"),
("GONDAL "," GDL"),
("GONDIA JN "," G"),
("GONDWANAVISAPUR "," GNVR"),
("GONEANA "," GNA"),
("GOOTY "," GY"),
("GOP JAM "," GOP"),
("GORAKHNATH "," GRKN"),
("GORAKHPUR CANT "," GKC"),
("GORAKHPUR JN "," GKP"),
("GORAUL "," GRL"),
("GORAYA "," GRY"),
("GOSALPUR "," GSPR"),
("GOSHAINGANJ "," GGJ"),
("GOSSAIGAON HAT "," GOGH"),
("GOTAN "," GOTN"),
("GOVINDGARH "," GVG"),
("GOVINDPUR ROAD "," GBX"),
("GOVINDPURI "," GOY"),
("GOWDAVALLI "," GWV"),
("GUDIVADA JN "," GDV"),
("GUDIYATTAM "," GYM"),
("GUDLAVALLERU "," GVL"),
("GUDUR JN "," GDR"),
("GUJHANDI "," GJD"),
("GULABHGANJ "," GLG"),
("GULABPURA "," GBP"),
("GULAOTHI "," GLH"),
("GULBARGA "," GR"),
("GULDHAR "," GUH"),
("GULEDAGUDDA RD "," GED"),
("GULZARBAGH "," GZH"),
("GUMANI "," GMAN"),
("GUMIA "," GMIA"),
("GUMMIDIPUNDI "," GPD"),
("GUNA "," GUNA"),
("GUNDARDEHI "," GDZ"),
("GUNTAKAL JN "," GTL"),
("GUNTUR JN "," GNT"),
("GURAMKHEDI "," GMD"),
("GURARU "," GRRU"),
("GURDASPUR "," GSP"),
("GURGAON "," GGN"),
("GURLA "," GQL"),
("GURNAY "," GRN"),
("GURPA "," GAP"),
("GURRA "," GRO"),
("GURSAHAIGANJ "," GHJ"),
("GURUVAYUR "," GUV"),
("GUSKARA "," GKH"),
("GUWAHATI "," GHY"),
("GWALIOR "," GWL"),
("GYANPUR ROAD "," GYN"),
("H NIZAMUDDIN "," NZM"),
("H SAHIB NANDED "," NED"),
("HABIBGANJ "," HBJ"),
("HAFIZPUR "," HZR"),
("HAFLONG HILL "," HFG"),
("HAIAGHAT "," HYT"),
("HAIDARNAGAR "," HDN"),
("HAIDERGARH "," HGH"),
("HAJIPUR JN "," HJP"),
("HALDAUR "," HLDR"),
("HALDI ROAD "," HLDD"),
("HALDIA "," HLZ"),
("HALDIBARI "," HDB"),
("HALDIPADA "," HIP"),
("HALDWANI "," HDW"),
("HALVAD "," HVD"),
("HAMIRA "," HMR"),
("HAMIRGARH "," HMG"),
("HAMIRPUR ROAD "," HAR"),
("HAMITONGANJ "," HOJ"),
("HANDIA KHAS "," HDK"),
("HANSI "," HNS"),
("HANUMANGARH JN "," HMH"),
("HAPA "," HAPA"),
("HAPUR "," HPU"),
("HARANGAJAO "," HJO"),
("HARANGUL "," HGL"),
("HARCHANDPUR "," HCP"),
("HARDA "," HD"),
("HARDAS BIGHA "," HDE"),
("HARDOI "," HRI"),
("HARDUA "," HDU"),
("HARICHANDANPUR "," HCNR"),
("HARIDWAR JN "," HW"),
("HARIHAR "," HRR"),
("HARINAGAR "," HIR"),
("HARIPPAD "," HAD"),
("HARIPUR "," HP"),
("HARISCHANDRPUR "," HCR"),
("HARISHANKER RD "," HSK"),
("HARMUTI "," HMY"),
("HARNAUT "," HRT"),
("HARPALGANJ "," HRPG"),
("HARPALPUR "," HPP"),
("HARRAD "," HRV"),
("HARRAWALA "," HRW"),
("HARRI "," HRB"),
("HARSAULI "," HSI"),
("HASANPARTHI RD "," HSP"),
("HASANPUR ROAD "," HPO"),
("HASIMARA "," HSA"),
("HASSAN "," HAS"),
("HATHBANDH "," HN"),
("HATHIDAH JN "," HTZ"),
("HATHRAS CITY "," HTC"),
("HATHRAS JN "," HRS"),
("HATIA "," HTE"),
("HATIKHALI "," HTL"),
("HATKANAGALE "," HTK"),
("HATPURAINI "," HPLE"),
("HAVERI "," HVR"),
("HAZARIBAGH RD "," HZD"),
("HELEM "," HML"),
("HIJILLI "," HIJ"),
("HILARA "," HLX"),
("HILSA "," HIL"),
("HIMAYATNAGAR "," HEM"),
("HIMMATANA "," HMI"),
("HIMMATNAGAR "," HMT"),
("HINDAUN CITY "," HAN"),
("HINDUPUR "," HUP"),
("HINGANGHAT "," HGT"),
("HINGOLI DECCAN "," HNL"),
("HIRA NAGAR "," HRNR"),
("HIRAKUD "," HKG"),
("HIRDAGARH "," HRG"),
("HIRNODA "," HDA"),
("HISAR "," HSR"),
("HODAL "," HDL"),
("HOJAI "," HJI"),
("HOLE ALUR "," HLAR"),
("HOLE NARSIPUR "," HLN"),
("HONNAVAR "," HNA"),
("HOSHANGABAD "," HBD"),
("HOSHIARPUR "," HSX"),
("HOSPET JN "," HPT"),
("HOSUR "," HSRA"),
("HOTGI "," HG"),
("HOWBADH JABLPUR "," HBG"),
("HOWRAH JN "," HWH"),
("HUBLI JN "," UBL"),
("HYDERABAD DECAN "," HYB"),
("ICHAULI "," ICL"),
("ICHCHPURAM "," IPM"),
("IDAPLLI "," IPL"),
("IDGAH AGRA JN "," IDH"),
("IGATPURI "," IGP"),
("IKKAR "," IKK"),
("IKLEHRA "," IKR"),
("INDARA JN "," IAA"),
("INDARGARH "," IDG"),
("INDI ROAD "," IDR"),
("INDORE JN BG "," INDB"),
("IRINJALAKUDA "," IJK"),
("IRUGUR "," IGU"),
("ISARDA "," ISA"),
("ISARWARA "," ISH"),
("ISLAMPUR "," IPR"),
("ISMAILA HARYANA "," ISM"),
("ISMAILPUR "," IMGE"),
("ITARSI JN "," ET"),
("ITOLA "," ITA"),
("ITWARI "," ITR"),
("IZZATNAGAR "," IZN"),
("JABALPUR "," JBP"),
("JADCHERLA "," JCL"),
("JAGADHRI "," JUD"),
("JAGADHRI WSHOP "," JUDW"),
("JAGADISHPUR "," JGD"),
("JAGATBELA "," JTB"),
("JAGDALPUR "," JDB"),
("JAGESHARGANJ "," JGJ"),
("JAGI ROAD "," JID"),
("JAGRAON "," JGN"),
("JAI SAMAND ROAD "," JYM"),
("JAIPUR "," JP"),
("JAIRAMNAGAR "," JRMG"),
("JAIS "," JAIS"),
("JAISALMER "," JSM"),
("JAITHARI "," JTI"),
("JAITWAR "," JTW"),
("JAJIWAL "," JWL"),
("JAJPUR K ROAD "," JJKR"),
("JAKHAL JN "," JHL"),
("JAKHALABANDHA "," JKB"),
("JAKHALAUN "," JLN"),
("JAKHANIAN "," JKN"),
("JAKHAPURA "," JKPR"),
("JAKHIM "," JHN"),
("JAKHVADA "," JKA"),
("JALALGANJ "," JLL"),
("JALALPUR DHAI "," JPD"),
("JALAMB JN "," JM"),
("JALANDHAR CANT "," JRC"),
("JALANDHAR CITY "," JUC"),
("JALESAR ROAD "," JLS"),
("JALESWAR "," JER"),
("JALGAON JN "," JL"),
("JALNA "," J"),
("JALOR "," JOR"),
("JALPAIGURI "," JPG"),
("JALPAIGURI ROAD "," JPE"),
("JALSU "," JAC"),
("JAM JODHPUR JN "," JDH"),
("JAM WANTHALI "," WTJ"),
("JAMA "," JAMA"),
("JAMALPUR JN "," JMP"),
("JAMBARA "," JMV"),
("JAMDHA "," JMD"),
("JAMIKUNTA "," JMKT"),
("JAMMU TAWI "," JAT"),
("JAMNAGAR "," JAM"),
("JAMTARA "," JMT"),
("JAMUI "," JMU"),
("JAMUNAMUKH "," JMK"),
("JANAKPUR ROAD "," JNR"),
("JANDIALA "," JNL"),
("JANGAON "," ZN"),
("JANGHAI JN "," JNH"),
("JANGIPUR ROAD "," JRLE"),
("JANWAL "," JOA"),
("JAORA "," JAO"),
("JAPLA "," JPL"),
("JARAIKELA "," JRA"),
("JARANDESHWAR "," JSV"),
("JARANGDIH "," JAN"),
("JAROLI "," JRLI"),
("JARWAL ROAD "," JLD"),
("JASIDIH JN "," JSME"),
("JASRA "," JSR"),
("JASWANTNAGAR "," JGR"),
("JATH ROAD "," JTRD"),
("JATINGA "," JTG"),
("JAUNPUR CITY "," JOP"),
("JAUNPUR JN "," JNU"),
("JAWAD ROAD "," JWO"),
("JAWAI BANDH "," JWB"),
("JAWALI "," JAL"),
("JAYASINGPUR "," JSP"),
("JAYNAGAR "," JYG"),
("JEHANABAD "," JHD"),
("JEJURI "," JJR"),
("JERUWA KHERA "," JRK"),
("JETALSAR JN "," JLR"),
("JEUR "," JEUR"),
("JEYPORE "," JYP"),
("JHAJHA "," JAJ"),
("JHALAWAR ROAD "," JHW"),
("JHALIDA "," JAA"),
("JHALWARA "," JLW"),
("JHANSI JN "," JHS"),
("JHANTIPAHARI "," JPH"),
("JHARGRAM "," JGM"),
("JHARSUGUDA JN "," JSG"),
("JHINJHAK "," JJK"),
("JIAGANJ "," JJG"),
("JIND JN "," JIND"),
("JIRADEI "," ZRDE"),
("JIRANIA "," JRNA"),
("JMLPR SHAIKHAN "," JPS"),
("JODHPUR JN "," JU"),
("JOGAL "," JOL"),
("JOGBANI "," JBN"),
("JOGENDRANAGAR "," JGNR"),
("JOGI MAGRA "," JOM"),
("JOGIGHOPA "," JPZ"),
("JOLARPETTAI "," JTJ"),
("JORAI "," JOQ"),
("JORAWARNAGAR JN "," JVN"),
("JORHAT TOWN "," JTTN"),
("JOYCHANDI PAHAR "," JOC"),
("JUGAUR "," JRR"),
("JUGPURA "," JRG"),
("JUJUMURA "," JUJA"),
("JUKEHI "," JKE"),
("JULANA "," JNA"),
("JUNAGADH JN "," JND"),
("JUNNOR DEO "," JNO"),
("JUTOGH "," JTO"),
("JWALAPUR "," JWP"),
("KABAKAPUTTUR "," KBPR"),
("KACHEGUDA "," KCG"),
("KACHHIA BRIDGE "," KCO"),
("KADAKAVUR "," KVU"),
("KADALUNDI "," KN"),
("KADAMBUR "," KDU"),
("KADAYNALLUR "," KDNL"),
("KADIRI "," KRY"),
("KADIYAN "," KYM"),
("KADUR "," DRU"),
("KAHALGAON "," CLG"),
("KAHILIYA "," KH"),
("KAIKOLUR "," KKLR"),
("KAILAHAT "," KYT"),
("KAILASAPURAM "," KLPM"),
("KAIMGANJ "," KMJ"),
("KAITHALKUCHI "," KTCH"),
("KAJGAON "," KJ"),
("KAJRA "," KJH"),
("KAJRAT NAWADIH "," KYF"),
("KAKARGHATTI "," KKHT"),
("KAKINADA PORT "," COA"),
("KAKINADA TOWN "," CCT"),
("KAKIRIGUMMA "," KKGM"),
("KAKORI "," KKJ"),
("KALA AKHAR "," KQE"),
("KALACHAND "," KQI"),
("KALANAUR KALAN "," KLNK"),
("KALANWALI "," KNL"),
("KALAPIPAL "," KPP"),
("KALHAR "," KAH"),
("KALI SINDH "," KSH"),
("KALIANPUR "," KAP"),
("KALIYANGANJ "," KAJ"),
("KALKA "," KLK"),
("KALLAKKUDI PLGH "," KKPM"),
("KALLAL "," KAL"),
("KALLKIRI "," KCI"),
("KALLURU "," KLU"),
("KALMITAR "," KLTR"),
("KALOL "," KLL"),
("KALPI "," KPI"),
("KALUNGA "," KLG"),
("KALUPARA GHAT "," KAPG"),
("KALYAN JN "," KYN"),
("KALYANPUR ROAD "," KPRD"),
("KAMAKHYA "," KYQ"),
("KAMAKHYAGURI "," KAMG"),
("KAMALAPURAM "," KKM"),
("KAMALGANJ "," KLJ"),
("KAMALNAGAR "," KMNR"),
("KAMALPURGRAM "," KLPG"),
("KAMARBANDHA ALI "," KXL"),
("KAMAREDDI "," KMC"),
("KAMARKUNDU "," KQU"),
("KAMPTEE "," KP"),
("KAMPUR "," KWM"),
("KAMSHET "," KMST"),
("KAMTAUL "," KML"),
("KANAKPURA "," KKU"),
("KANALAS JN "," KNLS"),
("KANAS ROAD "," KASR"),
("KANCHIPURAM "," CJ"),
("KANDAGHAT "," KDZ"),
("KANDARPUR "," KDRP"),
("KANDRA "," KND"),
("KANGINHAL "," KGX"),
("KANHANGAD "," KZE"),
("KANJARI BORIYAV "," KBRV"),
("KANKAHA "," KKAH"),
("KANKAVALI "," KKW"),
("KANKI "," KKA"),
("KANNAPURAM "," KPQ"),
("KANNAUJ "," KJN"),
("KANNUR "," CAN"),
("KANOH "," KANO"),
("KANPUR ANWRGANJ "," CPA"),
("KANPUR CENTRAL "," CNB"),
("KANSHBAHAL "," KXN"),
("KANSRAO "," QSR"),
("KANTABANJI "," KBJ"),
("KANTH "," KNT"),
("KANTHI P H "," KATI"),
("KANYAKUMARI "," CAPE"),
("KAPAN "," KPNA"),
("KAPASAN "," KIN"),
("KAPILAS ROAD "," KIS"),
("KAPSETI "," KEH"),
("KAPTANGANJ JN "," CPJ"),
("KAPURTHALA "," KXH"),
("KARAD "," KRD"),
("KARAGOLA ROAD "," CRR"),
("KARAIKAL "," KIK"),
("KARAIKKUDI JN "," KKDI"),
("KARAILA ROAD JN "," KRLR"),
("KARAJGI "," KJG"),
("KARAK BEL "," KKB"),
("KARAMNASA "," KMS"),
("KARANJGAON "," KAJG"),
("KARAUTA "," KWO"),
("KARBIGWAN "," KBN"),
("KARCHHA "," KDHA"),
("KARELI "," KY"),
("KARENGI "," KEG"),
("KAREPALLI "," KRA"),
("KARGI ROAD "," KGB"),
("KARHIYA BHADELI "," KYX"),
("KARIMGANJ JN "," KXJ"),
("KARIMNAGAR "," KRMR"),
("KARIMUDDIN PUR "," KMDR"),
("KARISATH "," KRS"),
("KARJAT "," KJT"),
("KARKELI "," KKI"),
("KARKHELI "," KEK"),
("KARMALI "," KRMI"),
("KARNA "," KAR"),
("KARNAL "," KUN"),
("KARONJI "," KJZ"),
("KARPURIGRAM "," KPGM"),
("KARTARPUR "," KRE"),
("KARUNAGAPALLI "," KPY"),
("KARUR "," KRR"),
("KARWAR "," KAWR"),
("KASARA "," KSRA"),
("KASARAGOD "," KGQ"),
("KASGANJ "," KSJ"),
("KASHI "," KEI"),
("KASHI CHAK "," KSC"),
("KASHIPUR "," KPV"),
("KASIMPUR "," KCJ"),
("KASTHA "," KSTA"),
("KATAKHAL JN "," KTX"),
("KATAREAH "," KTRH"),
("KATHARA ROAD "," KTRR"),
("KATHGODAM "," KGM"),
("KATHLEEGHAT "," KEJ"),
("KATHUA "," KTHU"),
("KATIHAR JN "," KIR"),
("KATNI "," KTE"),
("KATNI MURWARA "," KMZ"),
("KATOL "," KATL"),
("KATORA "," KTO"),
("KATPADI JN "," KPD"),
("KATRA "," KEA"),
("KATRASGARH "," KTH"),
("KATWA "," KWAE"),
("KAURHA "," KUF"),
("KAVALI "," KVZ"),
("KAVATHE MAHANKL "," KVK"),
("KAVUTARAM "," KVM"),
("KAYALPATTINAM "," KZY"),
("KAYANKULAM JN "," KYJ"),
("KAYAR "," KAYR"),
("KAZHAKUTTAM "," KZK"),
("KAZIPET JN "," KZJ"),
("KCG FALAKNUMA "," FM"),
("KECKHI "," KCKI"),
("KEDGAON "," KDG"),
("KEM "," KEM"),
("KENDPOSI "," KNPS"),
("KENDRAPARA ROAD "," KNPR"),
("KENDUJHARGARH "," KDJR"),
("KENGERI "," KGI"),
("KESAMUDRAM "," KDM"),
("KESHOD "," KSD"),
("KESHORAI PATAN "," KPTN"),
("KESINGA "," KSNG"),
("KEUTGUDA "," KTGA"),
("KHACHROD "," KUH"),
("KHADA "," KZA"),
("KHADKI "," KK"),
("KHAGA "," KGA"),
("KHAGARIA JN "," KGG"),
("KHAGRAGHAT ROAD "," KGLE"),
("KHAIRAR JN "," KID"),
("KHAIRTHAL "," KRH"),
("KHAJAULI "," KJI"),
("KHAJURAHO "," KURJ"),
("KHALARI "," KLRE"),
("KHALILABAD "," KLD"),
("KHALILPUR "," KIP"),
("KHALISPUR "," KSF"),
("KHALLIKOT "," KIT"),
("KHAMBHALIYA "," KMBL"),
("KHAMMAM "," KMT"),
("KHANA JN "," KAN"),
("KHANAPUR "," KNP"),
("KHANDALA "," KAD"),
("KHANDWA "," KNW"),
("KHANNA "," KNN"),
("KHANNA BANJARI "," KHBJ"),
("KHARAGPUR JN "," KGP"),
("KHARAK "," KHRK"),
("KHARIA KHANGARH "," KXG"),
("KHARIAR ROAD "," KRAR"),
("KHARSALIYA "," KRSA"),
("KHARSIA "," KHS"),
("KHARWA CHANDA "," KRCD"),
("KHATAULI "," KAT"),
("KHATIMA "," KHMA"),
("KHATIPURA "," KWP"),
("KHATU "," KHTU"),
("KHED "," KHED"),
("KHEDULI "," KQW"),
("KHERI SALWA "," KSW"),
("KHERLI "," KL"),
("KHETA SARAI "," KS"),
("KHIRKIYA "," KKN"),
("KHIRSADOH JN "," KUX"),
("KHODIYAR "," KHD"),
("KHODRI "," KOI"),
("KHOIRABARI "," KBY"),
("KHONGSARA "," KGS"),
("KHORASON ROAD "," KRND"),
("KHUDIRAM B PUSA "," KRBP"),
("KHUMTAI "," KUTI"),
("KHURAI "," KYE"),
("KHURDA ROAD JN "," KUR"),
("KHURDPUR "," KUPR"),
("KHURHAND "," KHU"),
("KHURIAL "," KWE"),
("KHURJA CITY "," KJY"),
("KHURJA JN "," KRJ"),
("KHUSROPUR "," KOO"),
("KILA KADAIYAM "," KKY"),
("KILA RAIPUR "," QRP"),
("KIM "," KIM"),
("KINWAT "," KNVT"),
("KIRAOLI "," KLB"),
("KIRATGARH "," KRTH"),
("KIRATPUR SAHIB "," KART"),
("KIRIHRAPUR "," KER"),
("KIRLOSKARVADI "," KOV"),
("KISHANGANJ "," KNE"),
("KISHANGARH "," KSG"),
("KISHANPUR "," KSP"),
("KIUL JN "," KIUL"),
("KOCHUVELI "," KCVL"),
("KODAIKANAL ROAD "," KQN"),
("KODERMA "," KQR"),
("KODIYAR MANDIR "," KDMR"),
("KODUMUDI "," KMD"),
("KODURU "," KOU"),
("KOELWAR "," KWR"),
("KOIRIPUR "," KEPR"),
("KOKRAJHAR "," KOJ"),
("KOLARAS "," KLRS"),
("KOLKATA "," KOAA"),
("KOLLAM JN "," QLN"),
("KOLLIKHUTAHA "," KKTA"),
("KOLNUR "," KOLR"),
("KONDAPALLI "," KI"),
("KONDAPURAM "," KDP"),
("KOPARGAON "," KPG"),
("KOPARIA "," KFA"),
("KOPPAL "," KBL"),
("KORAI HALT "," KRIH"),
("KORAPUT "," KRPU"),
("KORBA "," KRBA"),
("KOREGAON "," KRG"),
("KOSAMBA JN "," KSB"),
("KOSGI "," KO"),
("KOSI KALAN "," KSV"),
("KOT KAPURA "," KKP"),
("KOTA JN "," KOTA"),
("KOTABOMMALI "," KBM"),
("KOTALPUKUR "," KLP"),
("KOTAPAR ROAD "," KPRR"),
("KOTDWARA "," KTW"),
("KOTHARI ROAD "," KTHD"),
("KOTIKULAM "," KQK"),
("KOTLI KALAN "," KTKL"),
("KOTMA "," KTMA"),
("KOTMI SONAN HLT "," KTSH"),
("KOTSHILA "," KSX"),
("KOTTAPALLI "," KYOP"),
("KOTTAVALASA "," KTV"),
("KOTTAYAM "," KTYM"),
("KOVILPATTI "," CVP"),
("KOVVUR "," KVR"),
("KOZHIKODE "," CLT"),
("KRISHANRAJANAGA "," KRNR"),
("KRISHNA "," KSN"),
("KRISHNA CANAL "," KCC"),
("KRISHNA CH PURA "," KCV"),
("KRISHNARAJAPURM "," KJM"),
("KRISHNASHILLA "," KRSL"),
("KRISHNGR CTY JN "," KNJ"),
("KUCHAMAN CITY "," KMNC"),
("KUCHMAN "," KCA"),
("KUDACHI "," KUD"),
("KUDAL "," KUDL"),
("KUDALNAGAR "," KON"),
("KUDRA "," KTQ"),
("KUHURI "," KUU"),
("KULEM "," QLM"),
("KULHARIA "," KUA"),
("KULITALAI "," KLT"),
("KULITTHURAI "," KZT"),
("KULITTURAI WEST "," KZTW"),
("KULPAHAR "," KLAR"),
("KULTI "," ULT"),
("KUMARDUBI "," KMME"),
("KUMARGHAT "," KUGT"),
("KUMARHATTI "," KMTI"),
("KUMBAKONAM "," KMU"),
("KUMBHRAJ "," KHRJ"),
("KUMBLA "," KMQ"),
("KUMEDPUR "," KDPR"),
("KUMTA "," KT"),
("KUNDA HARNAMGNJ "," KHNM"),
("KUNDAPURA "," KUDA"),
("KUNEANGANJ "," KVG"),
("KUP "," KUP"),
("KUPGAL "," KGL"),
("KUPPAM "," KPN"),
("KURALI "," KRLI"),
("KURDUVADI "," KWV"),
("KURGUNTA "," KQT"),
("KURICHEDU "," KCD"),
("KURNOOL TOWN "," KRNT"),
("KURSELA "," KUE"),
("KURSEONG "," KGN"),
("KURUKSHETRA JN "," KKDE"),
("KURUMBUR "," KZB"),
("KUSMHI "," KHM"),
("KUTRALAM "," KTM"),
("KUTTIPPURAM "," KTU"),
("LABHA "," LAV"),
("LACHHMANPUR "," LMN"),
("LACHYAN "," LHN"),
("LADHOWAL "," LDW"),
("LADNUN "," LAU"),
("LAHERIA SARAI "," LSI"),
("LAHLI "," LHLL"),
("LAKADIYA "," LKZ"),
("LAKHERI "," LKE"),
("LAKHIMPUR "," LMP"),
("LAKHMINIA "," LKN"),
("LAKHTAR "," LTR"),
("LAKSAR JN "," LRJ"),
("LAKSHMIBAI NGR "," LMNR"),
("LAKSWA "," LXA"),
("LAL KUAN "," LKU"),
("LALGANJ "," LLJ"),
("LALGARH JN "," LGH"),
("LALGOLA "," LGL"),
("LALGOPALGANJ "," LGO"),
("LALGUDI "," LLI"),
("LALITPUR "," LAR"),
("LALPUR JAM "," LPJ"),
("LAMBHUA "," LBA"),
("LAMTA "," LTA"),
("LANGTING "," LGT"),
("LANJIGARH ROAD "," LJR"),
("LANKA "," LKA"),
("LAR ROAD "," LRD"),
("LASALGAON "," LS"),
("LASUR "," LSR"),
("LATEHAR "," LTHR"),
("LATHIDAD "," LTD"),
("LATUR "," LUR"),
("LATUR ROAD "," LTRR"),
("LAXMIPUR ROAD "," LKMR"),
("LEDO "," LEDO"),
("LEHRA GAGA "," LHA"),
("LELIGUMA "," LLGM"),
("LIDHORA KHURD "," LDA"),
("LILIYA MOTA "," LMO"),
("LIMBDI "," LM"),
("LIMKHEDA "," LMK"),
("LINGAMPALLI "," LPI"),
("LINGTI "," LNT"),
("LOHARU "," LHU"),
("LOHIAN KHAS JN "," LNK"),
("LOISINGHA "," LSX"),
("LOKMANYATILAK T "," LTT"),
("LONAND "," LNN"),
("LONAVALA "," LNL"),
("LONDA JN "," LD"),
("LORHA "," LOA"),
("LOWER HAFLONG "," LFG"),
("LUCKEESARAI JN "," LKR"),
("LUCKNOW CITY "," LC"),
("LUCKNOW NE "," LJN"),
("LUCKNOW NR "," LKO"),
("LUDHIANA JN "," LDH"),
("LUMDING JN "," LMG"),
("LUNI JN "," LUNI"),
("LUNI RICHHA "," LNR"),
("LUNKARANSAR "," LKS"),
("LUSA "," LUSA"),
("MACHELIPATNAM "," MTM"),
("MADAN MAHAL "," MML"),
("MADANAPALLE RD "," MPL"),
("MADAR "," MD"),
("MADDIKERA "," MKR"),
("MADDUR "," MAD"),
("MADGAON "," MAO"),
("MADHA "," MA"),
("MADHI "," MID"),
("MADHIRA "," MDR"),
("MADHOPUR PUNJAB "," MDPB"),
("MADHOSINGH "," MBS"),
("MADHUBANI "," MBI"),
("MADHUPUR JN "," MDP"),
("MADURAI JN "," MDU"),
("MADURANTAKAM "," MMK"),
("MADWARANI "," MWRN"),
("MAGHAR "," MHH"),
("MAHADANAPURAM "," MMH"),
("MAHAJAN "," MHJ"),
("MAHANAGAR "," MANG"),
("MAHASAMUND "," MSMD"),
("MAHBUBABAD "," MABD"),
("MAHBUBNAGAR "," MBNR"),
("MAHE "," MAHE"),
("MAHENDRAGARH "," MHRG"),
("MAHES KHUNT "," MSK"),
("MAHESANA JN "," MSH"),
("MAHESHMUNDA "," MMD"),
("MAHIDPUR ROAD "," MEP"),
("MAHMUDABAD AVDH "," MMB"),
("MAHOBA "," MBA"),
("MAHUDA "," MHQ"),
("MAHUR "," MXR"),
("MAHUVA JN "," MHV"),
("MAIBANG "," MBG"),
("MAIHAR "," MYR"),
("MAILANI "," MLN"),
("MAILONGDISA "," MGX"),
("MAINPURI "," MNQ"),
("MAIRWA "," MW"),
("MAJBAT "," MJBT"),
("MAJHAGAWAN "," MJG"),
("MAJHOLA PAKARYA "," MJZ"),
("MAJHOWLIA "," MJL"),
("MAJRI JN "," MJRI"),
("MAKHDUMPUR GAYA "," MDE"),
("MAKHU "," MXH"),
("MAKRANA JN "," MKN"),
("MAKRONIA "," MKRN"),
("MAKSI "," MKC"),
("MAKUDI "," MKDI"),
("MAKUM JN "," MJN"),
("MALAKHERA "," MKH"),
("MALAKPET KCG "," MXT"),
("MALANCHA "," MLNH"),
("MALANPUR "," MLAR"),
("MALARNA "," MLZ"),
("MALDA TOWN "," MLDT"),
("MALERKOTLA "," MET"),
("MALHARGARH "," MLG"),
("MALHOUR "," ML"),
("MALIHABAD "," MLD"),
("MALIPUR "," MLPR"),
("MALIYA HATINA "," MLHA"),
("MALIYA MIYANA "," MALB"),
("MALKAJGIRI "," MJF"),
("MALKAPUR "," MKU"),
("MALKAPUR ROAD "," MALK"),
("MALKHAID ROAD "," MQR"),
("MALKHEDI "," MAKR"),
("MALLANWALA KHAS "," MWX"),
("MALLAPUR "," MLP"),
("MALLARPUR "," MLV"),
("MALLESWARAM "," MWM"),
("MALLICKPUR HAT "," MKRH"),
("MALOUT "," MOT"),
("MALSIAN SHAHKHT "," MQS"),
("MALUR "," MLO"),
("MALWAN "," MWH"),
("MAMAN "," MOM"),
("MAMBALAM "," MBM"),
("MANAKSAR "," MNSR"),
("MANAMADURAI JN "," MNM"),
("MANANPUR "," MNP"),
("MANANWALA "," MOW"),
("MANAPARAI "," MPA"),
("MANAURI "," MRE"),
("MANCHESWAR "," MCS"),
("MANCHIRYAL "," MCI"),
("MANDA ROAD "," MNF"),
("MANDAGERE "," MGF"),
("MANDAL "," MDL"),
("MANDALGARH "," MLGH"),
("MANDAMARI "," MMZ"),
("MANDAPAM "," MMM"),
("MANDASA ROAD "," MMS"),
("MANDASOR "," MDS"),
("MANDAVALLI "," MDVL"),
("MANDAWAR M RD "," MURD"),
("MANDERDISA "," MYD"),
("MANDI ADAMPUR "," ADR"),
("MANDI BAMORA "," MABA"),
("MANDI DABWALI "," MBY"),
("MANDI DHANAURA "," MNDR"),
("MANDI DIP "," MDDP"),
("MANDRAK "," MXK"),
("MANDUADIH "," MUV"),
("MANDYA "," MYA"),
("MANENDRAGARH "," MDGR"),
("MANGAL MAHUDI "," MAM"),
("MANGALAGIRI "," MAG"),
("MANGALORE CNTL "," MAQ"),
("MANGALORE JN "," MAJN"),
("MANGAON "," MNI"),
("MANGLIYA GAON "," MGG"),
("MANGOLPURI "," MGLP"),
("MANIKGARH "," MAGH"),
("MANIKPUR JN "," MKP"),
("MANINAGAR "," MAN"),
("MANJESHWAR "," MJS"),
("MANJHI "," MHT"),
("MANKAPUR JN "," MUR"),
("MANKAR "," MNAE"),
("MANKATHA "," MKB"),
("MANMAD JN "," MMR"),
("MANNARGUDI "," MQ"),
("MANOHARGANJ "," MNJ"),
("MANOHARPUR "," MOU"),
("MANSA "," MSZ"),
("MANSI JN "," MNE"),
("MANTHRALAYAM RD "," MALM"),
("MANUGURU "," MUGR"),
("MANWATH ROAD "," MVO"),
("MARAMJHIRI "," MJY"),
("MARARIKULAM "," MAKM"),
("MARAUDA "," MXA"),
("MARGHERITA "," MRG"),
("MARIAHU "," MAY"),
("MARIANI JN "," MXN"),
("MARKAPUR ROAD "," MRK"),
("MARKONA "," MKO"),
("MAROLI "," MRL"),
("MARTHIPALAYAM "," MPLM"),
("MARWAR BHINMAL "," MBNL"),
("MARWAR JN "," MJ"),
("MARWAR LOHWAT "," MWT"),
("MARWAR MATHANYA "," MMY"),
("MARWAR MUNDWA "," MDW"),
("MARWASGRAM "," MWJ"),
("MASIT "," MST"),
("MASKANWA "," MSW"),
("MASUDAN "," MSDN"),
("MASUR "," MSR"),
("MATHURA CANT "," MRT"),
("MATHURA JN "," MTJ"),
("MATHURAPUR "," MUW"),
("MATMARI "," MTU"),
("MAU AIMMA "," MEM"),
("MAU JN "," MAU"),
("MAU RANIPUR "," MRPR"),
("MAUHARI "," MZH"),
("MAULA ALI "," MLY"),
("MAUR "," MAUR"),
("MAVELIKARA "," MVLK"),
("MAVLI JN "," MVJ"),
("MAYILADUTURAI J "," MV"),
("MAYYANAD "," MYY"),
("MCCLUSKIEGANJ "," MGME"),
("MECHEDA "," MCA"),
("MECHERI ROAD "," MCRD"),
("MEDAPADU "," MPU"),
("MEDCHAL "," MED"),
("MEERUT CANT "," MUT"),
("MEERUT CITY "," MTC"),
("MEGHNAGAR "," MGN"),
("MEHNAR ROAD "," MNO"),
("MEHSI "," MAI"),
("MEJA ROAD "," MJA"),
("MELATTUR "," MLTR"),
("MELMARUVATTUR "," MLMR"),
("MERALGRAM "," MQX"),
("MERAMANDOLIL "," MRDL"),
("MERTA ROAD JN "," MTD"),
("METUPALAIYAM "," MTP"),
("METUR DAM "," MTDM"),
("MHASODA DONGAR "," MSDG"),
("MHMDVD KHEDA RD "," MHD"),
("MIDNAPORE "," MDN"),
("MIGRENDISA "," MGE"),
("MIHINPURWA "," MIN"),
("MIHRAWAN "," MIH"),
("MILAK "," MIL"),
("MILAVITTAN "," MVN"),
("MINCHNAL "," MNL"),
("MIRAJ JN "," MRJ"),
("MIRANPUR KATRA "," MK"),
("MIRCHADHORI "," MCQ"),
("MIRTHAL "," MRTL"),
("MIRYALAGUDA "," MRGA"),
("MIRZA CHEUKI "," MZC"),
("MIRZAPALI "," MZL"),
("MIRZAPUR "," MZP"),
("MISRAULI "," MFL"),
("MISROD "," MSO"),
("MITHAPUR "," MTHP"),
("MIYAGAM KARJAN "," MYG"),
("MIYANA "," MINA"),
("MODINAGAR "," MDNR"),
("MODNIMB "," MLB"),
("MODRAN "," MON"),
("MOGA "," MOGA"),
("MOHADI PRGN LNG "," MHAD"),
("MOHANLALGANJ "," MLJ"),
("MOHITNAGAR "," MOP"),
("MOHIUDDINNAGAR "," MOG"),
("MOHOL "," MO"),
("MOHOPE "," MHPE"),
("MOKALSAR "," MKSR"),
("MOKAMEH JN "," MKA"),
("MONDH "," MOF"),
("MONU "," MANU"),
("MOOKAMBIKA ROAD "," BYNR"),
("MOR "," MOR"),
("MORADABAD "," MB"),
("MORAK "," MKX"),
("MORANHAT "," MRHT"),
("MORAPPUR "," MAP"),
("MORBI "," MVI"),
("MORDAD TANDA "," MWK"),
("MORENA "," MRA"),
("MORGRAM "," MGAE"),
("MORI BERA "," MOI"),
("MORINDA "," MRND"),
("MORKADHANA "," MKDN"),
("MORWANI "," MRN"),
("MOTH "," MOTH"),
("MOTICHUR "," MOTC"),
("MOTIPUR "," MTR"),
("MUDDANURU "," MOO"),
("MUDKHED "," MUE"),
("MUGHAL SARAI JN "," MGS"),
("MUHAMMADABAD "," MMA"),
("MUHAMMADGANJ "," MDJ"),
("MUKERIAN "," MEX"),
("MUKTAPUR "," MKPR"),
("MUKUNDARAYAPURM "," MCN"),
("MUL MARORA "," MME"),
("MULACALACHERUVU "," MCU"),
("MULANTURUTTI "," MNTT"),
("MULI ROAD "," MOL"),
("MULKI "," MULK"),
("MULTAI "," MTY"),
("MUMBAI CENTRAL "," BCT"),
("MUMBAI CST "," CSTM"),
("MUNABAO "," MBF"),
("MUNDERWA "," MND"),
("MUNGAOLI "," MNV"),
("MUNIGUDA "," MNGD"),
("MUNIRABAD "," MRB"),
("MUNROTURUTTU "," MQO"),
("MUPA "," MUPA"),
("MURADNAGAR "," MUD"),
("MURARAI "," MRR"),
("MURARPUR "," MPY"),
("MURDESHWAR "," MRDW"),
("MURI "," MURI"),
("MURIBAHAL "," MRBL"),
("MURKEONGSELEK "," MZS"),
("MURSHIDABAD "," MBB"),
("MURTAJAPUR "," MZR"),
("MURUKKAMPUZHA "," MQU"),
("MUSAFIR KHANA "," MFKA"),
("MUZAFFARNAGAR "," MOZ"),
("MUZAFFARPUR JN "," MFP"),
("MUZZAMPUR NRYN "," MZM"),
("MYSORE JN "," MYS"),
("N GHAZIABAD "," GZN"),
("N. PANAKUDI "," NPK"),
("NABADWIP DHAM "," NDAE"),
("NABENAGAR ROAD "," NBG"),
("NABHA "," NBA"),
("NABIPUR "," NIU"),
("NADAUJ "," NDU"),
("NADBAI "," NBI"),
("NADIAD JN "," ND"),
("NADIKODE "," NDKD"),
("NADWAN "," NDW"),
("NAGAON "," NGAN"),
("NAGAPPATTINAM "," NGT"),
("NAGAR "," NGE"),
("NAGAR UNTARI "," NUQ"),
("NAGARI "," NG"),
("NAGARIA SADAT "," NRS"),
("NAGARSOL "," NSL"),
("NAGARUR "," NRR"),
("NAGARWARA "," NWA"),
("NAGAUR "," NGO"),
("NAGBHIR JN "," NAB"),
("NAGDA JN "," NAD"),
("NAGER COIL TOWN "," NJT"),
("NAGERCOIL JN "," NCJ"),
("NAGINA "," NGG"),
("NAGIREDDIPALLI "," NRDP"),
("NAGORE "," NCR"),
("NAGPUR "," NGP"),
("NAGPUR ROAD "," NPRD"),
("NAHARKATIYA "," NHK"),
("NAIHATI JN "," NH"),
("NAILA "," NIA"),
("NAINI "," NYN"),
("NAINPUR JN "," NIR"),
("NAJIBABAD JN "," NBD"),
("NAKODAR JN "," NRO"),
("NAKSALBARI "," NAK"),
("NALANDA "," NLD"),
("NALBARI "," NLV"),
("NALGONDA "," NLDA"),
("NALHATI JN "," NHT"),
("NALWAR "," NW"),
("NAMBURU "," NBR"),
("NAMKON "," NKM"),
("NAMLI "," NLI"),
("NAMRUP "," NAM"),
("NAMTIALI "," NMT"),
("NANA "," NANA"),
("NANDALUR "," NRE"),
("NANDGANJ "," NDJ"),
("NANDGAON "," NGN"),
("NANDGAON ROAD "," NAN"),
("NANDURA "," NN"),
("NANDURBAR "," NDB"),
("NANDYAL "," NDL"),
("NANGAL DAM "," NLDM"),
("NANGLOI "," NNO"),
("NANGUNERI "," NNN"),
("NANPARA JN "," NNP"),
("NAPASAR "," NPS"),
("NARAINA "," NRI"),
("NARANGI "," NNGE"),
("NARANJIPUR "," NRGR"),
("NARANPUR "," NANR"),
("NARASAPUR "," NS"),
("NARASARAOPET "," NRT"),
("NARASINGAPALLI "," NASP"),
("NARAYANPET ROAD "," NRPD"),
("NARAYANPUR "," NNR"),
("NARAYNPUR ANANT "," NRPA"),
("NARELA "," NUR"),
("NARIAOLI "," NOI"),
("NARKATIAGANJ JN "," NKE"),
("NARKHER "," NRKR"),
("NARNAUL "," NNL"),
("NARSINGHPUR "," NU"),
("NARSIPATNAM RD "," NRP"),
("NARWANA JN "," NRW"),
("NASIK ROAD "," NK"),
("NASIRABAD "," NSD"),
("NASRALA "," NAS"),
("NATHNAGAR "," NAT"),
("NAUGACHIA "," NNA"),
("NAUPADA JN "," NWP"),
("NAUTANWA "," NTV"),
("NAVAGADH "," NUD"),
("NAVAPUR "," NWU"),
("NAVSARI "," NVS"),
("NAWA CITY "," NAC"),
("NAWABGANJ GONDA "," NGB"),
("NAWADAH "," NWD"),
("NAWAGAON "," NVG"),
("NAWANDGI "," NAW"),
("NAWAPARA ROAD "," NPD"),
("NAYA NANGAL "," NNGL"),
("NAYADUPETA "," NYP"),
("NAYAGAON "," NYO"),
("NAYAGARH "," NYG"),
("NAZARETH "," NZT"),
("NAZIRGANJ "," NAZJ"),
("NEKONDA "," NKD"),
("NELLORE "," NLR"),
("NEORA "," NEO"),
("NEPANAGAR "," NPNR"),
("NERAL "," NRL"),
("NERGUNDI "," NRG"),
("NEW ALIPURDAUR "," NOQ"),
("NEW AMRAVAT "," NAVI"),
("NEW BONGAIGAON "," NBQ"),
("NEW COOCH BEHAR "," NCB"),
("NEW DELHI "," NDLS"),
("NEW FARAKKA JN "," NFK"),
("NEW GUNTUR "," NGNT"),
("NEW JALPAIGURI "," NJP"),
("NEW KATNI JN "," NKJ"),
("NEW MAL JN "," NMZ"),
("NEW MAYNAGURI "," NMX"),
("NEW MISAMARI "," NMM"),
("NEW TINSUKIA JN "," NTSK"),
("NEYYATTINKARA "," NYY"),
("NIDADAVOLU JN "," NDD"),
("NIDAMANGALAM "," NMJ"),
("NIDUBROLU "," NDO"),
("NIGAURA "," NIQ"),
("NIGOHAN "," NHN"),
("NIHALGARH "," NHH"),
("NILAKANTHESWAR "," NKW"),
("NILAMBUR ROAD "," NIL"),
("NILESHWAR "," NLE"),
("NILOKHERI "," NLKR"),
("NIM KA THANA "," NMK"),
("NIMACH "," NMH"),
("NIMBAHERA "," NBH"),
("NIMBAL "," NBL"),
("NIMBHORA "," NB"),
("NIMTITA "," NILE"),
("NINGALA JN "," NGA"),
("NIPHAD "," NR"),
("NIRA "," NIRA"),
("NIRAKARPUR "," NKP"),
("NISUI "," NSU"),
("NIVARI "," NEW"),
("NIWAR "," NWR"),
("NIWAS ROAD "," NWB"),
("NIZAMABAD "," NZB"),
("NOAMUNDI "," NOMD"),
("NOKHA "," NOK"),
("NORLA ROAD "," NRLR"),
("NORTH LAKHIMPUR "," NLP"),
("NOWROZABAD "," NRZB"),
("NRYNPUR TATWAR "," NNW"),
("NSC BOSE J GOMO "," GMO"),
("NUAGAON "," NXN"),
("NUJELLA "," NUJ"),
("NUMALIGARH "," NMGY"),
("NUNKHAR "," NRA"),
("NURMAHAL "," NRM"),
("NUZVID "," NZD"),
("OBAIDULLA GANJ "," ODG"),
("OBRA DAM "," OBR"),
("OBULAVARIPALLI "," OBVP"),
("ODELA "," OEA"),
("OKHA "," OKHA"),
("OKHLA "," OKA"),
("OLD MALDA "," OMLF"),
("OMALUR "," OML"),
("ONDAGRAM "," ODM"),
("ONGOLE "," OGL"),
("ORAI "," ORAI"),
("ORGA "," ORGA"),
("OSIYAN "," OSN"),
("OTTAPPALAM "," OTP"),
("PACHHAPUR "," PCH"),
("PACHOR ROAD "," PFR"),
("PACHORA JN "," PC"),
("PADADHARI "," PDH"),
("PADAMPUR "," PDF"),
("PADUBIDRI "," PDD"),
("PAHARPUR "," PRP"),
("PAKALA JN "," PAK"),
("PAKUR "," PKR"),
("PALACHAURI "," PCLI"),
("PALAKKAD "," PGT"),
("PALAKKODU "," PCV"),
("PALAKOLLU "," PKO"),
("PALAM "," PM"),
("PALANPUR JN "," PNU"),
("PALASA "," PSA"),
("PALEJ "," PLJ"),
("PALGHAR "," PLG"),
("PALGHAT TOWN "," PGTN"),
("PALI MARWAR "," PMY"),
("PALIA KALAN "," PLK"),
("PALLIYADI "," PYD"),
("PALWAL "," PWL"),
("PAMAN "," PMN"),
("PAMBAN JN "," PBM"),
("PANAGARH "," PAN"),
("PANCH PIPILA "," PCN"),
("PANCHGRAM "," PNGM"),
("PANDABESWAR "," PAW"),
("PANDAUL "," PDW"),
("PANDAVAPURA "," PANP"),
("PANDHARPUR "," PVR"),
("PANDHURNA "," PAR"),
("PANELI MOTI "," PLM"),
("PANGAON "," PNF"),
("PANIAHWA "," PNYA"),
("PANIPAT JN "," PNP"),
("PANKI "," PNK"),
("PANOLI "," PAO"),
("PANPOSH "," PPO"),
("PANRUTI "," PRT"),
("PANSKURA "," PKU"),
("PANVEL "," PNVL"),
("PAPANASAM "," PML"),
("PARADIP "," PRDP"),
("PARADOL "," PRDL"),
("PARAIYA "," PRY"),
("PARAMAKKUDI "," PMK"),
("PARAS "," PS"),
("PARASHSHALA "," PASA"),
("PARASIA "," PUX"),
("PARASNATH "," PNME"),
("PARAVUR "," PVU"),
("PARBATI "," PRB"),
("PARBHANI JN "," PBN"),
("PARDI "," PAD"),
("PAREWADI "," PRWD"),
("PARISAL "," PSL"),
("PARLI VAIJNATH "," PRLI"),
("PARMANANDPUR "," PMU"),
("PARPANANGADI "," PGI"),
("PARSABAD "," PSB"),
("PARSIPUR "," PRF"),
("PARSODA "," PSD"),
("PARTAPGARH JN "," PBH"),
("PARTUR "," PTU"),
("PARVATIPURAM "," PVP"),
("PARVATIPURAM TN "," PVPT"),
("PASRAHA "," PSR"),
("PATARA "," PTRE"),
("PATAUDI ROAD "," PTRD"),
("PATHANKOT "," PTK"),
("PATHARDIH JN "," PEH"),
("PATHARIA "," PHA"),
("PATHARKANDI "," PTKD"),
("PATHRI "," PRI"),
("PATHSALA "," PBL"),
("PATIALA "," PTA"),
("PATNA JN "," PNBE"),
("PATNA SAHEB "," PNC"),
("PATRANGA "," PTH"),
("PATRATU "," PTRU"),
("PATTAMBI "," PTB"),
("PATTIKKAD "," PKQ"),
("PAVURCHUTRAM "," PCM"),
("PAWAPURI ROAD "," PQE"),
("PAYAGPUR "," PDR"),
("PAYANGADI "," PAZ"),
("PAYYANUR "," PAY"),
("PAYYOLI "," PYOL"),
("PEDAKAKANI HALT "," PDKN"),
("PEDANA "," PAV"),
("PEDDAPALLI "," PDPL"),
("PEDDAVADIAPUDI "," PVD"),
("PEDDEMPET "," PPZ"),
("PEMBARTI "," PBP"),
("PENCHARTHAL "," PEC"),
("PENDEKALLU "," PDL"),
("PENDRA ROAD "," PND"),
("PENNADAM "," PNDM"),
("PENUKONDA "," PKD"),
("PEPPEGANJ "," PJ"),
("PERALAM JN "," PEM"),
("PERAMBUR "," PER"),
("PERNEM "," PERN"),
("PETTAIVAYATALAI "," PLI"),
("PHAGWARA JN "," PGW"),
("PHALODI JN "," PLCJ"),
("PHAPHAMAU JN "," PFM"),
("PHAPHUND "," PHD"),
("PHEPHNA JN "," PEP"),
("PHESAR "," PES"),
("PHILLAUR JN "," PHR"),
("PHULERA JN "," FL"),
("PHULPUR "," PLP"),
("PHULWARI SHARIF "," PWS"),
("PHULWARTANR "," PLJE"),
("PHUSRO "," PUS"),
("PIDUGURALLA "," PGRL"),
("PILAMEDU "," PLMD"),
("PILER "," PIL"),
("PILI BANGAN "," PGK"),
("PILIBHIT JN "," PBE"),
("PILKHUA "," PKW"),
("PIMPALKHUTI "," PMKT"),
("PIMPRI "," PMP"),
("PINDLAI "," PQL"),
("PINDRA ROAD "," PDRD"),
("PINDRAI "," PDE"),
("PIPALSANA "," PLS"),
("PIPAR ROAD JN "," PPR"),
("PIPARIYA "," PPI"),
("PIPLIA "," PIP"),
("PIPLOD JN "," PPD"),
("PIPRAICH "," PPC"),
("PIPRAIGAON "," PIA"),
("PIPRALA "," PFL"),
("PIRAVAM ROAD "," PVRD"),
("PIRPAINTI "," PPT"),
("PITAMBARPUR "," PMR"),
("PITHAPURAM "," PAP"),
("PLASSEY "," PLY"),
("PMBAKVL SHANDY "," PBKS"),
("POCHARAM "," PCZ"),
("PODANUR JN "," PTJ"),
("POKHRAYAN "," PHN"),
("POKLA "," PKF"),
("POKRAN "," POK"),
("POLUR "," PRL"),
("PONDURU "," PDU"),
("PONMLAI GLD RCK "," GOC"),
("PORBANDAR "," PBR"),
("PORJANPUR "," PRNR"),
("POTHAHI "," PFT"),
("POTHIA "," POT"),
("POTKAPALLI "," PTKP"),
("POTUL "," POZ"),
("POWERKHEDA "," PRKD"),
("POWERPET "," PRH"),
("PRANTIK "," PNE"),
("PRAYAG "," PRG"),
("PUDUCHERRY "," PDY"),
("PUDUKAD "," PUK"),
("PUDUKKOTTAI "," PDKT"),
("PUGALUR "," PGR"),
("PULGAON JN "," PLO"),
("PULLAMPET "," PMT"),
("PUNARAKH "," PHK"),
("PUNDHAG "," PNW"),
("PUNDI "," PUN"),
("PUNE JN "," PUNE"),
("PUNKUNNAM "," PNQ"),
("PUNPUN "," PPN"),
("PUNSIA "," PNSA"),
("PUNTAMBA "," PB"),
("PURANPUR "," PP"),
("PURI "," PURI"),
("PURNA JN "," PAU"),
("PURNIA JN "," PRNA"),
("PURULIA JN "," PRR"),
("PUTTUR "," PUT"),
("PWN KLAKNDER RD "," PQN"),
("QUILANDI "," QLD"),
("RADHANPUR "," RDHP"),
("RADHIKAPUR "," RDP"),
("RAE BARELI JN "," RBL"),
("RAFIGANJ "," RFJ"),
("RAGAUL "," RGU"),
("RAGHAVAPURAM "," RGPM"),
("RAGHUNATHPALLI "," RGP"),
("RAGHUNATHPUR "," RCTC"),
("RAGHURAJ SINGH "," RRS"),
("RAHAMA "," RHMA"),
("RAHIMABAD "," RBD"),
("RAHIMATPUR "," RMP"),
("RAHURI "," RRI"),
("RAICHUR "," RC"),
("RAIGANJ "," RGJ"),
("RAIGARH "," RIG"),
("RAIGIR "," RAG"),
("RAIKA BAGH "," RKB"),
("RAIMEHATPUR "," MTPR"),
("RAIPUR JN "," R"),
("RAIRAKHOL "," RAIR"),
("RAISI "," RSI"),
("RAIWALA "," RWL"),
("RAJ GANGPUR "," GP"),
("RAJ NANDGAON "," RJN"),
("RAJA KA SAHASPR "," RJK"),
("RAJA KI MANDI "," RKM"),
("RAJALDESAR "," RJR"),
("RAJAMUNDRY "," RJY"),
("RAJANAGAR "," RJA"),
("RAJAPALAYAM "," RJPM"),
("RAJAPUR ROAD "," RAJP"),
("RAJGARH "," RHG"),
("RAJGHAT NARORA "," RG"),
("RAJGIR "," RGD"),
("RAJGRAM "," RJG"),
("RAJKHARSAWAN JN "," RKSN"),
("RAJKOT JN "," RJT"),
("RAJMANE "," RM"),
("RAJPURA JN "," RPJ"),
("RAJULA JN "," RLA"),
("RAKHA MINES "," RHE"),
("RAM CHAURA ROAD "," RMC"),
("RAM NAGAR J K "," RMJK"),
("RAMAN "," RMN"),
("RAMANAGARAM "," RMGM"),
("RAMANATHAPURAM "," RMD"),
("RAMANNAPET "," RMNP"),
("RAMBHA "," RBA"),
("RAMBHADDARPUR "," RBZ"),
("RAMDEVRA "," RDRA"),
("RAMESWARAM "," RMM"),
("RAMGANJ MANDI "," RMA"),
("RAMGARH CANT "," RMT"),
("RAMGARHWA "," RGH"),
("RAMGUNDAM "," RDM"),
("RAMNA "," RMF"),
("RAMNAGAR "," RMR"),
("RAMNAGAR BENGAL "," RMRB"),
("RAMPUR "," RMU"),
("RAMPUR BAZAR "," RMPB"),
("RAMPUR DUMRA "," RDUM"),
("RAMPUR HAT "," RPH"),
("RAMPURA PHUL "," PUL"),
("RANAGHAT JN "," RHA"),
("RANAPRATAPNAGAR "," RPZ"),
("RANAVAV "," RWO"),
("RANCHI "," RNC"),
("RANCHI ROAD "," RRME"),
("RANGALITING "," RNGG"),
("RANGAPARA NORTH "," RPAN"),
("RANGIYA JN "," RNY"),
("RANI "," RANI"),
("RANIBENNUR "," RNR"),
("RANIGANJ "," RNG"),
("RANIWARA "," RNV"),
("RANOLI "," RNO"),
("RANPUR "," RUR"),
("RAOTI "," RTI"),
("RASRA "," RSR"),
("RASULABAD "," RUB"),
("RASURIYA "," RYS"),
("RATANGARH JN "," RTGH"),
("RATANPUR "," RPUR"),
("RATANPURA "," RTP"),
("RATHDHANA "," RDDE"),
("RATLAM JN "," RTM"),
("RATNAGIRI "," RN"),
("RAULI "," RUL"),
("RAVER "," RV"),
("RAVINDRAKHANI "," RVKH"),
("RAXAUL JN "," RXL"),
("RAY "," RAY"),
("RAYAGADA "," RGDA"),
("RAYALCHERUVU "," RLO"),
("RAYANAPAD "," RYP"),
("RAYBAG "," RBG"),
("RAZAMPETA "," RJP"),
("RECHNI ROAD "," RECH"),
("REJINAGAR "," REJ"),
("REN "," REN"),
("RENGALI "," RGL"),
("RENIGUNTA JN "," RU"),
("RENUKUT "," RNQ"),
("REOTI "," ROI"),
("REOTI B KHERA "," RBK"),
("REWA "," REWA"),
("REWARI "," RE"),
("RINGAS JN "," RGS"),
("RISAMA "," RSA"),
("RISHIKESH "," RKSH"),
("RISIA "," RS"),
("RITHI "," REI"),
("RJNDR NGR BIHAR "," RJPB"),
("RNINGR JLPAIGRI "," RQJ"),
("ROBERTS GANJ "," RBGJ"),
("ROHA "," ROHA"),
("ROHTAK JN "," ROK"),
("ROORKEE "," RK"),
("ROSHANPUR "," RHN"),
("ROTEGAON "," RGO"),
("ROURKELA "," ROU"),
("ROWRIAH SDG "," RWH"),
("ROWTA BAGAN "," RWTB"),
("ROZA JN "," ROZA"),
("RUDAULI "," RDL"),
("RUDRAPUR CITY "," RUPC"),
("RUKADI "," RKD"),
("RUNKHERA "," RNH"),
("RUPAMAU "," RUM"),
("RUPAUND "," RPD"),
("RUPBAS "," RBS"),
("RUPNAGAR "," RPAR"),
("RUPNARAYANPUR "," RNPR"),
("RUPRA ROAD "," RPRD"),
("RUPSA JN "," ROP"),
("RURA "," RURA"),
("RUSERA GHAT "," ROA"),
("RUTHIYAI "," RTA"),
("S BHAKHTIYARPUR "," SBV"),
("SABARMATI JN "," SBI"),
("SABAUR "," SBO"),
("SACHIN "," SCH"),
("SADAT "," SDT"),
("SADISOPUR "," SDE"),
("SADULPUR JN "," SDLP"),
("SAFDARGANJ "," SGJ"),
("SAFEDABAD "," SFH"),
("SAGADAPATA "," SGDP"),
("SAGAR JAMBAGARU "," SRF"),
("SAGARDIGHI "," SDI"),
("SAGAULI JN "," SGL"),
("SAGONI "," SAO"),
("SAHARANPUR "," SRE"),
("SAHARSA JN "," SHC"),
("SAHARSRAKUND "," SHSK"),
("SAHATWAR "," STW"),
("SAHIBABAD "," SBB"),
("SAHIBGANJ JN "," SBG"),
("SAHIBPUR KML JN "," SKJ"),
("SAHIBZADA ASNGR "," SASN"),
("SAHJANWA "," SWA"),
("SAI P NILAYAM "," SSPN"),
("SAIDRAJA "," SYJ"),
("SAINAGAR SHIRDI "," SNSI"),
("SAINTALA "," SFC"),
("SAINTHIA "," SNT"),
("SAIYID SARAWAN "," SYWN"),
("SAKALDIHA "," SLD"),
("SAKHI GOPAL "," SIL"),
("SAKHPUR "," SKR"),
("SAKLESHPUR "," SKLR"),
("SAKRI JN "," SKI"),
("SAKRIGALI JN "," SLJ"),
("SAKTESGARH "," SKGH"),
("SAKTI "," SKT"),
("SALAIA "," SYA"),
("SALAMATPUR "," SMT"),
("SALAR "," SALE"),
("SALAUNA "," SLNA"),
("SALBONI "," SLB"),
("SALEKASA "," SKS"),
("SALEM JN "," SA"),
("SALEM TOWN "," SXT"),
("SALEMPUR JN "," SRU"),
("SALICHAUKA ROAD "," SCKR"),
("SALKAROAD "," SLKR"),
("SALMARI "," SRI"),
("SALOGRA "," SLR"),
("SAMAKHIALI B G "," SIOB"),
("SAMALKHA "," SMK"),
("SAMALKOT JN "," SLO"),
("SAMALPATTI "," SLY"),
("SAMASTIPUR JN "," SPJ"),
("SAMBA "," SMBX"),
("SAMBALPUR "," SBP"),
("SAMBALPUR CITY "," SBPY"),
("SAMBALPUR ROAD "," SBPD"),
("SAMBHAR LAKE "," SBR"),
("SAMDHARI JN "," SMR"),
("SAMLAYA JN "," SMLA"),
("SAMNAPUR "," SMC"),
("SAMPLA "," SPZ"),
("SAMSI "," SM"),
("SANAHWAL "," SNL"),
("SANAND "," SAU"),
("SANAT NAGAR "," SNF"),
("SANCHI "," SCI"),
("SANDILA "," SAN"),
("SANEH ROAD "," SNX"),
("SANGARIA "," SGRA"),
("SANGAT "," SGF"),
("SANGLI "," SLI"),
("SANGMESHWAR "," SGR"),
("SANGOLA "," SGLA"),
("SANGRUR "," SAG"),
("SANICHARA "," SAC"),
("SANJAN "," SJN"),
("SANKARANKOVIL "," SNKL"),
("SANKARIDURG "," SGE"),
("SANKARPUR "," SNQ"),
("SANOSRA "," SOA"),
("SANSARPUR "," SNRR"),
("SANT ROAD "," SAT"),
("SANTALDIH "," SNTD"),
("SANTALPUR "," SNLR"),
("SANTRAGACHI JN "," SRC"),
("SANVERDAM CHUCH "," SVM"),
("SAPATGRAM "," SPX"),
("SAPEKHATI "," SPK"),
("SAPHALE "," SAH"),
("SARAGBUNDIA "," SRBA"),
("SARAI "," SAI"),
("SARAI CHANDI "," SYC"),
("SARAI KANSRAI "," SQN"),
("SARAI MIR "," SMZ"),
("SARANGPUR "," SFW"),
("SARBAHARA "," SBRA"),
("SARDARGRAM "," SDGM"),
("SARDARNAGAR "," SANR"),
("SARDIHA "," SUA"),
("SAREIGRAM "," SGAM"),
("SARERI "," SSR"),
("SARKONI "," SIQ"),
("SARNATH "," SRNT"),
("SARUPATHAR "," SZR"),
("SASARAM "," SSM"),
("SASTHANKOTTA "," STKT"),
("SATARA "," STR"),
("SATHAJAGAT "," STJT"),
("SATHIAON "," SAA"),
("SATHIN ROAD "," SWF"),
("SATNA "," STA"),
("SATROD "," STD"),
("SATTENAPALLE "," SAP"),
("SATUR "," SRT"),
("SAUGOR "," SGO"),
("SAVARDA "," SVX"),
("SAVARKUNDLA "," SVKD"),
("SAVDA "," SAV"),
("SAWAI MADHOPUR "," SWM"),
("SAWANTWADI ROAD "," SWV"),
("SAYAN "," SYN"),
("SBB JOGULAMBA H "," SBBJ"),
("SEALDAH "," SDAH"),
("SECUNDERABAD JN "," SC"),
("SEHORE "," SEH"),
("SELU "," SELU"),
("SEMAPUR "," SMO"),
("SENCHOA JN "," SCE"),
("SENDRA "," SEU"),
("SENGOTTAI "," SCT"),
("SEOHARA "," SEO"),
("SEORAPHULI "," SHE"),
("SERAM "," SEM"),
("SERAMPORE "," SRP"),
("SEVAGRAM "," SEGM"),
("SEWAPURI "," SWPR"),
("SEYDUNGANALLUR "," SDNR"),
("SHADNAGAR "," SHNR"),
("SHAHABAD "," SDB"),
("SHAHBAD MARKNDA "," SHDM"),
("SHAHDOL "," SDL"),
("SHAHGANJ JN "," SHG"),
("SHAHJEHANPUR "," SPN"),
("SHAHPUR PATOREE "," SPP"),
("SHAJAPUR "," SFY"),
("SHAKTI NAGAR "," SKTN"),
("SHAKURBASTI "," SSB"),
("SHALIMAR "," SHM"),
("SHAM CHAURASI "," SCQ"),
("SHAMGARH "," SGZ"),
("SHAMLI "," SMQL"),
("SHANKARGARH "," SRJ"),
("SHANKARPALLI "," SKP"),
("SHEDBAL "," SED"),
("SHEGAON "," SEG"),
("SHEIKPURA "," SHK"),
("SHEOPRASADNAGER "," SPDR"),
("SHERTALAI "," SRTL"),
("SHIKARA "," SKY"),
("SHIKOHABAD JN "," SKB"),
("SHIMOGA "," SME"),
("SHIMOGA TOWN "," SMET"),
("SHIRRAVDE "," SIW"),
("SHIRUD "," SHF"),
("SHIUPUR "," SOP"),
("SHIVAJI BRIDGE "," CSB"),
("SHIVAJINAGAR "," SVJR"),
("SHIVANARAYANPUR "," SVRP"),
("SHIVNAGAR "," SHNG"),
("SHIVPURI "," SVPI"),
("SHIVRAMPUR "," SWC"),
("SHOGHI "," SGS"),
("SHOLAVANDAN "," SDN"),
("SHOLINGHUR "," SHU"),
("SHORANUR JN "," SRR"),
("SHRI GANGANAGAR "," SGNR"),
("SHRI MADHOPUR "," SMPR"),
("SHRI MAHABIRJI "," SMBJ"),
("SHRIBDRYA LATHI "," SBLT"),
("SHRIDHAM "," SRID"),
("SHRIGONDA ROAD "," SGND"),
("SHRIRAJNAGAR "," SAGR"),
("SHRIRANGAPATNA "," S"),
("SHUJAATPUR "," SJT"),
("SHUJALPUR "," SJP"),
("SHYAMPURI "," SMPA"),
("SIBSAGAR TOWN "," SRTN"),
("SIDDHPUR "," SID"),
("SIGADAM "," SGDM"),
("SIHAPAR "," SIPR"),
("SIHO "," SIHO"),
("SIHOR GUJARAT "," SOJN"),
("SIHORA ROAD "," SHR"),
("SIKANDRA RAO "," SKA"),
("SIKAR JN "," SIKR"),
("SIKARPAI "," SKPI"),
("SILAO "," SILO"),
("SILAPATHAR "," SPTR"),
("SILAUT "," SLT"),
("SILCHAR "," SCL"),
("SILGHAT TOWN "," SHTT"),
("SILIGURI JN "," SGUJ"),
("SILLI "," SLF"),
("SIMALUGURI JN "," SLGR"),
("SIMARIA "," SAE"),
("SIMBHOOLI "," SMBL"),
("SIMHACHALAM "," SCM"),
("SIMLA "," SML"),
("SIMULTALA "," STL"),
("SINDHUDURG "," SNDD"),
("SINDI "," SNI"),
("SINDKHEDA "," SNK"),
("SINDRIBLOCK HUT "," SDBH"),
("SINGAPURAM ROAD "," SPRD"),
("SINGARAM "," SGRM"),
("SINGARAYAKONDA "," SKM"),
("SINGHPUR "," SNGP"),
("SINGRAULI "," SGRL"),
("SINI JN "," SINI"),
("SIRARI "," SRY"),
("SIRATHU "," SRO"),
("SIRHIND JN "," SIR"),
("SIRKAZHI "," SY"),
("SIROHI ROAD "," SOH"),
("SIRPUR KAGAZNGR "," SKZR"),
("SIRPUR TOWN "," SRUR"),
("SIRSA "," SSA"),
("SIRSAUL "," SSL"),
("SISVINHALLI "," SVHE"),
("SISWA BAZAR "," SBZ"),
("SITABINJ "," STBJ"),
("SITAFAL MANDI "," STPD"),
("SITALPUR "," STLR"),
("SITAMARHI "," SMI"),
("SITAPUR "," STP"),
("SITAPUR CANT "," SCC"),
("SITAPUR CITY "," SPC"),
("SITARAMPUR "," STN"),
("SIURI "," SURI"),
("SIVAGANGA "," SVGA"),
("SIVAKASI "," SVKS"),
("SIWAITH "," SWE"),
("SIWAN JN "," SV"),
("SLEEMANABAD RD "," SBD"),
("SNARAYAN CHAPIA "," SNC"),
("SOHAGPUR "," SGP"),
("SOHWAL "," SLW"),
("SOJAT ROAD "," SOD"),
("SOLAN "," SOL"),
("SOLAPUR JN "," SUR"),
("SOMESAR "," SOS"),
("SOMNATH "," SMNH"),
("SOMPETA "," SPT"),
("SON NAGAR "," SEB"),
("SONADA "," SAD"),
("SONAGIR "," SOR"),
("SONALLI "," SI"),
("SONBARSA KCHERI "," SBM"),
("SONDAD "," SNV"),
("SONEGAON "," SNN"),
("SONGADH "," SGD"),
("SONI "," SONI"),
("SONIPAT "," SNP"),
("SONPUR JN "," SEE"),
("SONTALAI "," SQL"),
("SONUA "," SWR"),
("SORBHOG JN "," SBE"),
("SORO "," SORO"),
("SORON "," SRNK"),
("SRI DUNGARGARH "," SDGH"),
("SRI KALAHASTI "," KHT"),
("SRIKAKULAM ROAD "," CHE"),
("SRIKRISHN NAGAR "," SKN"),
("SRIRAMNAGAR "," SRNR"),
("SRIRANGAM "," SRGM"),
("SRIVAIKUNTAM "," SVV"),
("SRIVILLIPUTTUR "," SVPR"),
("SUBEDARGANJ "," SFG"),
("SUBRAHMANYA ROA "," SBHR"),
("SUBZI MANDI "," SZM"),
("SUDAMDIH "," SDMD"),
("SUDHANI "," SUD"),
("SUDSAR "," SDF"),
("SUHSARAI "," SOW"),
("SUISA "," SSIA"),
("SUJANGARH "," SUJH"),
("SUJANPUR "," SJNP"),
("SUKINDA ROAD "," SKND"),
("SUKRITIPUR "," SQF"),
("SULGARE "," SGRE"),
("SULLURUPETA "," SPE"),
("SULTANGANJ "," SGG"),
("SULTANPUR "," SLN"),
("SULTANPUR LODI "," SQR"),
("SUMMER HILL "," SHZ"),
("SUMRERI "," SMRR"),
("SUNAM "," SFM"),
("SURAIMANPUR "," SIP"),
("SURAJPUR ROAD "," SJQ"),
("SURAT "," ST"),
("SURATGARH JN "," SOG"),
("SURATHKAL "," SL"),
("SURENDRANAGAR "," SUNR"),
("SURENDRANAGAR G "," SRGT"),
("SURGAON BANJARI "," SGBJ"),
("SURIAWAN "," SAW"),
("SUWASRA "," SVA"),
("SWARUPGANJ "," SRPJ"),
("TADAKALPUDI "," TPY"),
("TADALI "," TAE"),
("TADEPALLIGUDEM "," TDD"),
("TADIPATRI "," TU"),
("TADWAL "," TVL"),
("TAHSIL FATEHPUR "," TSF"),
("TAIABPUR "," TBR"),
("TAKARI "," TKR"),
("TAKIA "," TQA"),
("TAKU "," TAKU"),
("TALAKHAJURI "," TLKH"),
("TALBAHAT "," TBT"),
("TALCHER "," TLHR"),
("TALCHER ROAD "," TLHD"),
("TALCHHAPAR "," TLC"),
("TALEGAON "," TGN"),
("TALGUPPA "," TLGP"),
("TALJHARI "," TLJ"),
("TALVADYA "," TLV"),
("TALWANDI "," TWB"),
("TAMBARAM "," TBM"),
("TAMLUK "," TMZ"),
("TANAKPUR "," TPU"),
("TANDA URMAR "," TDO"),
("TANDUR "," TDU"),
("TANGIRIAPAL "," TGRL"),
("TANGLA "," TNL"),
("TANGRA "," TRA"),
("TANGUTURU "," TNR"),
("TANKUPPA "," TKN"),
("TANUKU "," TNKU"),
("TANUR "," TA"),
("TAPA "," TAPA"),
("TAPRI "," TPZ"),
("TARADEVI "," TVI"),
("TARANA ROAD "," TAN"),
("TARAORI "," TRR"),
("TARAPITH ROAD "," TPF"),
("TAREGNA "," TEA"),
("TARGAON "," TAZ"),
("TARIGOPPULA "," TGU"),
("TARIKERE JN "," TKE"),
("TARLUPADU "," TLU"),
("TARSARAI "," TRS"),
("TARU "," TR"),
("TATANAGAR JN "," TATA"),
("TATIBAHAR "," TBH"),
("TATISILWAI "," TIS"),
("TEGHRA "," TGA"),
("TEHTA "," THA"),
("TELAM "," TQM"),
("TELIAMURA "," TLMR"),
("TELO "," TELO"),
("TELTA "," TETA"),
("TENALI JN "," TEL"),
("TENGANMADA "," TGQ"),
("TENKASI JN "," TSI"),
("TETULMARI "," TET"),
("THAKURGANJ "," TKG"),
("THAKURTOTA "," TKH"),
("THALASSERY "," TLY"),
("THALWARA "," TLWA"),
("THAN JN "," THAN"),
("THANA BIHPUR JN "," THB"),
("THANDLA RD "," THDR"),
("THANE "," TNA"),
("THANJAVUR "," TJ"),
("THERUBALI "," THV"),
("THIRUVARUR JN "," TVR"),
("THIVIM "," THVM"),
("THRISUR "," TCR"),
("THURIA "," THUR"),
("TIHU "," TIHU"),
("TIKIRI "," TKRI"),
("TIKUNIA "," TQN"),
("TILAK BRIDGE "," TKJ"),
("TILARU "," TIU"),
("TILAYA "," TIA"),
("TILDA "," TLD"),
("TILHAR "," TLH"),
("TILONIYA "," TL"),
("TIMARNI "," TBN"),
("TIMMAPUR "," TMX"),
("TINDIVANAM "," TMV"),
("TINPAHAR JN "," TPH"),
("TINSUKIA JN "," TSK"),
("TIPKAI "," TPK"),
("TIPTUR "," TTR"),
("TIRALDIH "," TUL"),
("TIRCHRPALI FORT "," TP"),
("TIRORA "," TRO"),
("TIRUCHCHIRAPALI "," TPJ"),
("TIRUCHENDUR "," TCN"),
("TIRUCHRPALI TWN "," TPTN"),
("TIRUKOILUR "," TRK"),
("TIRUMANGALAM "," TMQ"),
("TIRUNELVELI "," TEN"),
("TIRUNNAVAYA "," TUA"),
("TIRUPADRIPULYUR "," TDPR"),
("TIRUPARANKNDRM "," TDN"),
("TIRUPATI "," TPTY"),
("TIRUPATTUR JN "," TPT"),
("TIRUPPUR "," TUP"),
("TIRUR "," TIR"),
("TIRUTTANGAL "," TTL"),
("TIRUTTANI "," TRT"),
("TIRUVALLA "," TRVL"),
("TIRUVALLUR "," TRL"),
("TIRUVANNAMALAI "," TNM"),
("TIRUVERUMBUR "," TRB"),
("TISUA "," TSA"),
("TITABAR "," TTB"),
("TITLAGARH "," TIG"),
("TIVARI "," TIW"),
("TO DARJEELING "," DJRZ"),
("TODARPUR "," TDP"),
("TOHANA "," TUN"),
("TOMKA "," TMKA"),
("TORANAGALLU "," TNGL"),
("TORANG "," TRAN"),
("TORI "," TORI"),
("TRIKARPUR "," TKQ"),
("TRIUPUNITTURA "," TRTR"),
("TRIVANDRUM CNTL "," TVC"),
("TRIVANDRUM PETT "," TVP"),
("TSUNDURU "," TSR"),
("TUGLAKABAD "," TKD"),
("TULJAPUR "," TGP"),
("TUMKUR "," TK"),
("TUMSAR ROAD "," TMR"),
("TUNDLA JN "," TDL"),
("TUNG "," TUNG"),
("TUNI "," TUNI"),
("TURAVUR "," TUVR"),
("TUTI MELUR "," TME"),
("TUTICORIN "," TN"),
("TUVVUR "," TUV"),
("TWINING GANJ "," TWG"),
("UCHANA "," UCA"),
("UDAIPUR CITY "," UDZ"),
("UDALGURI "," ULG"),
("UDALKACHAR "," UKR"),
("UDGIR "," UDGR"),
("UDHAMPUR "," UHP"),
("UDHNA JN "," UDN"),
("UDUPI "," UD"),
("UDVADA "," UVD"),
("UGAR KHURD "," UGR"),
("UGRASENPUR "," URPR"),
("UJALVAV "," UJ"),
("UJHANI "," UJH"),
("UJIARPUR "," UJP"),
("UJJAIN JN "," UJN"),
("UKHRA "," UKA"),
("UKLANA "," UKN"),
("ULHASNAGAR "," ULNR"),
("ULLAL "," ULL"),
("ULUBARIA "," ULB"),
("UMAR TALI "," UTA"),
("UMARIA "," UMR"),
("UMBARGAM ROAD "," UBR"),
("UMDANAGAR "," UR"),
("UMED "," UMED"),
("UMRI "," UMRI"),
("UNA HIMACHAL "," UHL"),
("UNCHAHAR JN "," UCR"),
("UNCHHERA "," UHR"),
("UNDASA MADHAWPU "," UDM"),
("UNJALUR "," URL"),
("UNJHA "," UJA"),
("UNNAO JN "," ON"),
("UNTARE ROAD "," URD"),
("UPLETA "," UA"),
("UPPAL "," OPL"),
("UPPALA "," UAA"),
("UREN "," UREN"),
("URGA "," URGA"),
("URULI "," URI"),
("USALAPUR "," USL"),
("USMANABAD "," UMD"),
("UTARLAI "," UTL"),
("UTRAHTIA "," UTR"),
("UTTUKULI "," UKL"),
("VADAKARA "," BDJ"),
("VADGAON "," VDN"),
("VADLAMANNADU "," VMD"),
("VADODARA JN "," BRC"),
("VAIBHAVWADI RD "," VBW"),
("VAIKOM "," VARD"),
("VAILAPUZHA "," VPZ"),
("VALAPATTANAM "," VAPM"),
("VALAPPADI G HLT "," VGE"),
("VALIVADE "," VV"),
("VALLIKUNNU "," VLI"),
("VALLIYUR "," VLY"),
("VALSAD "," BL"),
("VANCHIMANIYACHI "," MEJ"),
("VANGAON "," VGN"),
("VANIYAMBADI "," VN"),
("VANIYAMBALAM "," VNB"),
("VAPI "," VAPI"),
("VARAHI "," VRX"),
("VARANASI CITY "," BCY"),
("VARANASI JN "," BSB"),
("VARANGAON "," VNA"),
("VARKALA "," VAK"),
("VARTEJ "," VTJ"),
("VASAD JN "," VDA"),
("VASAI ROAD "," BSR"),
("VASCO DA GAMA "," VSG"),
("VEDAYAPALEM "," VDE"),
("VEER "," VEER"),
("VELANKANNI "," VLKN"),
("VELLANKANNI "," VLNK"),
("VELLORE CANT "," VLR"),
("VENDODU "," VDD"),
("VENKATAGIRI "," VKI"),
("VENKATNAGRA "," VKR"),
("VERAVAL "," VRL"),
("VERKA JN "," VKA"),
("VETAPALEMU "," VTM"),
("VIDISHA "," BHS"),
("VIDYAPATINAGAR "," VPN"),
("VIDYASAGAR "," VDS"),
("VIJAY PUR "," VJP"),
("VIJAYAWADA JN "," BZA"),
("VIJIYPUR JAMMU "," VJPJ"),
("VIKARABAD JN "," VKB"),
("VIKRAMGARH ALOT "," VMA"),
("VIKRAMNAGAR "," VRG"),
("VILAVADE "," VID"),
("VILAYATKALAN RD "," VYK"),
("VILLUPARAM JN "," VM"),
("VINDHYACHAL "," BDL"),
("VINUKONDA "," VKN"),
("VIRAMGAM JN "," VG"),
("VIRAR "," VR"),
("VIRAVASARAM "," VVM"),
("VIRBHADRA "," VRH"),
("VIRPUR "," VRR"),
("VIRUDUNAGAR JN "," VPT"),
("VISAPUR "," VPR"),
("VISHAKAPATNAM "," VSKP"),
("VISHNUPURAM "," VNUP"),
("VISHRAMBAG "," VRB"),
("VISHVAMITRI "," VS"),
("VISWANATH CHRLI "," VNE"),
("VITHISVARANKOL "," VDL"),
("VIVEKA VIHAR "," VVB"),
("VIZIANAGRAM JN "," VZM"),
("VRIDHACHALAM JN "," VRI"),
("VYARA "," VYA"),
("VYASNAGAR "," VYN"),
("WADAKANCHERI "," WKI"),
("WADHWAN CITY "," WC"),
("WADI "," WADI"),
("WADIARAM "," WDR"),
("WADRENGDISA "," WDA"),
("WADSA "," WSA"),
("WALAJAH ROAD JN "," WJR"),
("WANI "," WANI"),
("WANKANER JN "," WKR"),
("WANPARTI ROAD "," WPR"),
("WANSJALIYA "," WSJ"),
("WARANGAL "," WL"),
("WARDHA JN "," WR"),
("WARIA "," OYR"),
("WARIS ALEGANJ "," WRS"),
("WARORA "," WRR"),
("WASHIM "," WHM"),
("WATHAR "," WTR"),
("WAZERGANJ "," WZJ"),
("WENA "," WENA"),
("WHITEFIELD "," WFD"),
("WIHIRGAON "," VHGN"),
("WIRUR "," WIRR"),
("WYNDHAMGANJ "," WDM"),
("YADGIR "," YG"),
("YALVIGI "," YLG"),
("YAMUNA BDG AGRA "," JAB"),
("YELHANKA JN "," YNK"),
("YEOLA "," YL"),
("YERRAGUNTLA "," YA"),
("YESVANTPUR JN "," YPR"),
("YUSUFPUR "," YFP"),
("ZAFARABAD JN "," ZBD"),
("ZAHIRABAD "," ZB"),
("ZAMANIA "," ZNA"),
("ZAWAR "," ZW")]
    C1.executemany(EnterStation, StationName)
    Station.commit()
    print("Done")
station()
